### ISSUE TITLE
ld: warning: linking against a dylib which is not safe for use in application extensions

### ISSUE THREAD

**Issue by skela** [luispadron/UICircularProgressRing#101]
## Bug Report

Warning when using library obtained from Carthage in an Extension Widget.

#### Version

v 2.1.1

![screen shot 2018-06-19 at 14 52 07](https://user-images.githubusercontent.com/58268/41598438-745fda3c-73d0-11e8-8dc6-92be85c352ee.png)

**Comment by luispadron** [comment]
This is not a bug caused by the library. 

This is an issue you must fix within your code and how you use your extension, please look on line for further resources.

**Comment by skela** [comment]
@luispadron not so sure about that, seeing as I've other libraries pulled down from Carthage that don't have the warning.

I think the fix is rather simple, let me show you what build setting affects it:

PromiseKit - Does not cause warning

![screen shot 2018-06-20 at 22 29 06](https://user-images.githubusercontent.com/58268/41682993-b00cf9ca-74d9-11e8-87d2-722bfaa37b29.png)

UICircularProgressRing - Causes warning

![screen shot 2018-06-20 at 22 29 32](https://user-images.githubusercontent.com/58268/41683012-c00255c8-74d9-11e8-9fbb-8a8351ccc77f.png)

**Comment by luispadron** [comment]
Ahh, thanks for bringing this up. I did some searching and people seemed to be saying it was a project setting so didn’t think I could do anything about that. I’ll look into fixing this by changing that setting, will push a new version soon

**Comment by skela** [comment]
@luispadron thanks that fixed it!
