### ISSUE TITLE
Start progress with initial value

### ISSUE THREAD

**Issue by gabreho** [luispadron/UICircularProgressRing#105]
I've tried to set an initial values to the progress ring and then start the progress animation but it always starts from 0, is it possible to do this?

**Comment by luispadron** [comment]
Please follow issue guidelines before posting, they're there for a reason... 

There are `minValue` and `maxValue` properties, the `minValue` is what the progress ring starts at when initialized. You can either change the min to be something else, or you can `startProgress(to: 10, duration: 0)` this means it will quickly change to that position without animating thus you can set "initial value". Please read the docs for more info.
