### ISSUE TITLE
No CircularProgressRingView?

### ISSUE THREAD

**Issue by EBMCreative** [luispadron/UICircularProgressRing#107]
So Maybe I am loosing my mind but the version 3 has no CircularProgressRingView to put in to interface builder.

**Comment by luispadron** [comment]
The changelog clearly state it’s been renamed to `UICircularProgressRing`

**Comment by EBMCreative** [comment]
Yes I understand that but I can't get it to load into the storyboard.  I have tried to use UICircularProgressRing for the class and module name and it does not work.  So I maybe a total moron and newbie and I am fine with that but I don't know how to see it in the storyboard.

**Comment by luispadron** [comment]
If you installed it via cocoapods, there’s currently a bug where it doesn’t work with interface builder. This isn’t something I can fix, cocoapods team is working on it

**Comment by EBMCreative** [comment]
I used carthage.

**Comment by luispadron** [comment]
Carthage doesn’t work with interface builder as the README states
