### ISSUE TITLE
failed to render and update auto layout status for ViewController(BYZ-38-t0r)

### ISSUE THREAD

**Issue by Daeyangman** [luispadron/UICircularProgressRing#108]
_If it's a question about something that is happening within your code base, either post a small amount of code, [email me](mailto:luis@luispadron.com) project if you want to keep it private, or post an example project where I can try to assist.
Make sure to communicate back and keep issue updated or it will be closed_

## Version

- Version = ios 11.4 

## Details

- Has the question been answered [here](https://github.com/luispadron/UICircularProgressRing/issues?utf8=✓&q=label%3Aquestion) before?
  Not yet
- Please provide as much detail as possible below
 Full Error message:failed to render and update auto layout status for ViewController(BYZ-38-t0r):dlopen(UICircularProgressRing.framework,1):no suitable image found. Did find: UICircularProgressRing.framework:required code signature missing for 'UICircularProgressRing.framework' Main.storyboard

  - As i tried to import this library on my own project , i got a error message like as ahead.
    I followed to do like as you expressed using Cocoapods.
    But , I couldn't solve this problem.
    How to do that ? 
    Thank you.
    I had just done 
    1) create test project 
    2) sudo gem install cocoapods
    3) in project folder , pod init ( confused sequence)
    4) pod setup 
    5) pod init "got a message declare twice"
    6) in Podfile , changed ios version '9.0' -> '11.4'
         added pod 'UICircularProgressRing' 
    7) pod install
        (got a message 'Automatically assigning platform `ios` with version `11.4` on target `CircleTest` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`") 
   
    8) done .xcworkspace 
    9) and then create uiview 
    10) tried to class -> UICircularProgressRingView  , but i couldn't do that 
          only UICircularProgressRing is available.
     11) after that, i got a message.

How to solve it? 

Thank you

**Comment by Daeyangman** [comment]
Thank you for quick answer.
If i'm using version of Xcode is higher than 9.0 , can't i use this library?

**Comment by luispadron** [comment]
I haven’t tried it, but Xcode 10 is in beta and this hasn’t been built with Swift 4.2
