### ISSUE TITLE
Problems after updating to 3.0.0

### ISSUE THREAD

**Issue by mekarpatx** [luispadron/UICircularProgressRing#109]
My project was working just fine with 2.2.0
After i've updated from 2.2.0 to 3.0.0 with cocoapods, i get the error saying : 
"Use of undeclared type 'UICircularProgressRingView'"

I didn't changed anything in the code. Just the pod update. 

The file has "import UICircularProgressRing" as before. 
And the UICircularProgressRing is not visible in the storyboard anymore.

Any ideas? Thanks

**Comment by luispadron** [comment]
Please read the [CHANGELOG](https://github.com/luispadron/UICircularProgressRing/blob/master/CHANGELOG.md)

The view has been renamed to `UICircularProgressRing`.

Also, please follow guidelines before posting an issue...
