### ISSUE TITLE
Use of undeclared type 'UICircularProgressRingView'

### ISSUE THREAD

**Issue by sandeepbol** [luispadron/UICircularProgressRing#111]
#### Version

3.0.0

#### Overview of what you tried to do

After updating to version 3.0.0 from 2.1.1, I am getting the following error. 

> Use of undeclared type 'UICircularProgressRingView'

Is UICircularProgressRingView renamed to 'UICircularProgressRing'? If yes, the documentation should be updated? When using 'UICircularProgressRing' instead, there is an error while using setProgress(_:_) not found. What is that renamed to? startProgress(_:_)?

**Comment by luispadron** [comment]
Please read the docs and changelog, everything is documented

**Comment by wvteijlingen** [comment]
The readme says to use `UICircularProgressRingView`. However, the docs and the playground use `UICircularProgressRing`. I think the readme should be updated here.

**Comment by luispadron** [comment]
Yah must’ve forgotten to update the README. However, it’s really important that people follow posting guidelines. I get about 3 issues a day asking the same questions that can be answered by either searching other issues or reading the documentation that me and the other contributors have spent a ton of time working on.

**Comment by wvteijlingen** [comment]
Yeah I agree. Compliments on the documentation. 100% documented is always refreshing to see :).

I've created a pull request for this small change in the readme: https://github.com/luispadron/UICircularProgressRing/pull/114.

**Comment by luispadron** [comment]
Already updated it haha, but thanks!

**Comment by sandeepbol** [comment]
kudos @luispadron really neat library. The intention wasn't to crib but to point out that README were probably not updated. I had figured the changes though by looking into the source code already :) Thanks again for replying!

**Comment by sandeepbol** [comment]
On a smaller side-note, whenever you get time, you can update the gif for storyboard integration as well. It still uses 'UICircularProgressRingView'.

**Comment by luispadron** [comment]
Thanks for pointing that out I’ll update when I get a chance.
