### ISSUE TITLE
Problem with startProgress

### ISSUE THREAD

**Issue by codelover123** [luispadron/UICircularProgressRing#115]
#### Version

v3.1.0

#### Overview of what you tried to do

Hi, I have progressRing implemented in storyboard, connected via outlet to controller and when I try to startProgress it returns exc_bad_address. What could be the cause? When I downgraded to 3.0.0 it works. 

```swift
progressRing.startProgress(to: 8.9, duration: 0.75) {
                    print("Hello there")
                }
```

**Comment by luispadron** [comment]
This is not an issue with the library, check your outlets. In the future please don’t post about bugs related to your own project. Use stackoverflow instead.

**Comment by codelover123** [comment]
Yea, right, when it works with previous version and doesn't work with newer one it means it is problem with my project. Ok.

**Comment by luispadron** [comment]
Well could you post a more detailed example, how am I supposed to debug with what you gave me above?

**Comment by luispadron** [comment]
Also, the ring has been renamed to UICircularProgressRing so if your outlets use the old name they will cause a bad memory read because of storyboard
