### ISSUE TITLE
Unable to get version 3.1.0 from Cocoapods

### ISSUE THREAD

**Issue by daniel-choi** [luispadron/UICircularProgressRing#117]
Hello, thanks for the great library!

It seems like the latest version has not been updated in Cocoapods specs. I've updated the pod repo but I still can't download 3.1.0. I can, however, download 3.0.0.

**Comment by luispadron** [comment]
Thanks for letting me know. Must have forgotten to push to trunk, will do so soon.

**Comment by luispadron** [comment]
Now available on CocoPods!
