### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by anismansuri** [luispadron/UICircularProgressRing#118]
## Bug Report

:warning: **Your issue will be closed if these are not filled out**. :warning:

#### Version

3.1.0

#### Overview of what you tried to do

I updated pod from 2.2.0 to 3.1.0.

#### What is the expected outcome?

It should work as it was working before

#### What is the actual outcome?

It crashes when I redirect to my circular view controller
 required public init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        // Call the internal initializer
        initialize()
    }

App crashed on this line:
super.init(coder: aDecoder)

**Comment by luispadron** [comment]
Did you read the changelog and docs? The view has been renamed to `UICircularProgressRing` which will cause crashing if you have the old name in a storyboard.

**Comment by anismansuri** [comment]
Yes, I already read the changelog, renamed UICircularProgressRing too.

**Comment by luispadron** [comment]
Well I’m going to need more information than what you’ve provided to help you out
