### ISSUE TITLE
Propery 'patternForDashes' issue

### ISSUE THREAD

**Issue by RomainBSQT** [luispadron/UICircularProgressRing#12]
Hello !

There is a slight issue on the _patternForDashes_, property.
When it is used, you only take into account the first member of the provided array.

In your _UICircularProgressRingLayer_ L173 :
`outerPath.setLineDash(patternForDashes, count: 1, phase: 0.0)`
and it should (according to me) be :
`outerPath.setLineDash(patternForDashes, count: patternForDashes.count, phase: 0.0)`

Without fixing this, you can't set a proper dash pattern, only the length of a dash is taken into account.

Hope it helps.

**Comment by luispadron** [comment]
Ahh, according to [Apple](https://developer.apple.com/reference/uikit/uibezierpath/1624373-setlinedash) you are right! 

I added this fix, and its on [version 1.2.1](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.2.1)

Feel free to `pod update` or `git pull`

Thanks for bringing it up!

**Comment by RomainBSQT** [comment]
That's what i'd call reactivity ;)

Thanks !
