### ISSUE TITLE
errors being thrown from the pod can't build project

### ISSUE THREAD

**Issue by photog0411** [luispadron/UICircularProgressRing#121]
I've had the UICirularProgressRing library in my app for quite a while now and it's been working fine.   Today I did a pod install to install another pod (the Siren pod library) and when I run Xcode now, UICircularProgressRing is having these errors > as you can see the errors are in the pod files themselves not in my code:

![screen shot 2018-08-11 at 12 07 48 am](https://user-images.githubusercontent.com/18505956/43988045-dfec13d0-9cfa-11e8-9283-73d1b2b58b9b.png)

**Comment by photog0411** [comment]
BTW I am using the latest version of UICircularProgress ring.

**Comment by photog0411** [comment]
d: file not found: /Users/Greg/Library/Developer/Xcode/DerivedData/fotocast-dxnejjpmgortzbbbdvxxkoejtvjh/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/UICircularProgressRing.build/Objects-normal/arm64/UICircularProgressRingView.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by photog0411** [comment]
after cleaning the project I. now get these errors instead, which I don't understand because my project is swift and your library is swift so I don't know why the pod is looking for objective c:

![screen shot 2018-08-11 at 12 16 34 am](https://user-images.githubusercontent.com/18505956/43988086-efd7feac-9cfb-11e8-9042-f94943010a09.png)

**Comment by luispadron** [comment]
This is because it’s been renamed to `UICircularProgressRing`. Please read the changelog and docs before posting an issue.

**Comment by photog0411** [comment]
I did already rename all references of UICircularProgressRingView to UICircularProgressRing 7 days ago. It has been working fine since then, but today after doing a pod install to install another pod to my project only now I am getting the errors.

You can see from the photo that UICircularProgressRingView is in your framework, not anywhere in my project files.

**Comment by photog0411** [comment]
check and see I am not using the old name anywhere in my project

![screen shot 2018-08-11 at 12 40 49 am](https://user-images.githubusercontent.com/18505956/43988232-3786cad2-9cff-11e8-8aed-9a11b1cc7757.png)

**Comment by luispadron** [comment]
Well, could you please fill out the required information before posting an issue so I can have a better idea of your environment? The lib compiles fine so I'd image it's an issue with some caching on your end, or Xcode being dumb as usual.
What version of Xcode, CocoaPods, UICircularProgressRing and iOS are you running?

**Comment by luispadron** [comment]
Things to try:

1. Clean CocoaPods cache, `pod cache clean --all`
2. Update CocoaPods repo `pod repo update`
3. Reinstall pods `pod install`

**Comment by photog0411** [comment]
xcode - latest non-beta version
uicircularprogressring - 3.2.0
iOS - 10.13.5 high Sierra
cocoa pods - 1.5.3

steps I have already performed:

1) clean and rebuild project (didn't work)
2) delete derived data (didn't work)
3) pod update (didn't work)
4) reinstall xcode (didn't work)
5) run system cleaner (didn't work)


The weird thing is if I delete my local working copy of my project and checkout the latest version again from GitHub, the project builds fine. But as soon as I add any more pods to my project, then your pod is throwing the errors. 

Do you think there's some kind of conflict with yours and the Siren pod? that is the one I'm trying to install

**Comment by luispadron** [comment]
Could you try the steps I outlined above and see if that does anything? Seems like a Pods caching issue

**Comment by photog0411** [comment]
ok that worked thank you!!! I tried googling how to do something like that with the pod thing before but couldn't find anything

**Comment by luispadron** [comment]
No problem, glad we got it sorted.

**Comment by photog0411** [comment]
it was this one that fixed it by the way
pod cache clean --all
