### ISSUE TITLE
Pause/continue doesn't seem to work correctly

### ISSUE THREAD

**Issue by nickdnk** [luispadron/UICircularProgressRing#124]
#### Version

3.3.0
iOS 11.4

#### Overview of what you tried to do

In response to the application resigning to background (`UIApplicationWillResignActiveNotification`), I call pause, and in response to becoming active (`UIApplicationDidBecomeActiveNotification`), I call continue. 

I would very much like to use this, because I think it's cool, but as it's currently implemented this pause-bug is a dealbreaker.

#### What is the expected outcome?

I would expect the counter to start where it left off - where it was paused.

#### What is the actual outcome?

It almost immediately calls its completion block after calling continue. I've debugged it and it seems to be around 2-5 seconds even though my progress is set from 0 to 100 with 0 min and 100 max value, 60 second duration, and I pause it a few seconds after starting it. I have no idea where it gets these numbers.

#### Post sample code or example here

Code is proprietary, so I cannot post it here, but the scenario in my explanation should be easily reproducible.

#### Have you tried fixing this yourself?

I tried debugging the logic that determines where to start off the timer that calls the execution block, but I simply don't understand what this method does. Specifically I don't understand `ringLayer.convertTime(CACurrentMediaTime(), from: nil)`. I tried fetching the `value` and `currentValue` variables in the continue method to use those instead (something like `timerShouldStartAfter = duration - (duration * currentValue / maxValue)`, which mathematically provides the correct result), but these always return 100 even though the current value is clearly something in between.

**Comment by nickdnk** [comment]
I've been looking closer at the mechanics. I managed to get the timer to properly pick up where it left off like this:

Define

`private var pausedAtValue : TimeInterval = 0`

Then in `pauseProgress()`:

`if let fireTime = completionTimer?.fireDate {
            pausedAtValue = fireTime.timeIntervalSince(Date())
        } else {
            pausedAtValue =  0;
        }`

And in `continueProgress()`:

`completionTimer = Timer.scheduledTimer(timeInterval: pausedAtValue,
                                               target: self,
                                               selector: #selector(animationDidComplete),
                                               userInfo: completion,
                                               repeats: false)`

However, this doesn't fix the fact that the animation is stopped entirely and does not resume when the app comes back from the background. This seems to be a common problem: https://stackoverflow.com/questions/7568567/restoring-animation-where-it-left-off-when-app-resumes-from-background

**Comment by nickdnk** [comment]
Also, would it be possible to remove the fatal error when trying to continue or pause something that hasn't been paused or started? It really serves no purpose other than having to code around. It could just as well fail silently.

**Comment by luispadron** [comment]
Closed in #128
