### ISSUE TITLE
the style of the progress ring cannot show as I want

### ISSUE THREAD

**Issue by NancyZY** [luispadron/UICircularProgressRing#13]
As I read the [document](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularProgressRingView.html#/s:vC22UICircularProgressRing26UICircularProgressRingView9viewStyleSi),I set the value of viewStyle equal 2, but the radius of inner ring is smaller than  outer ring, rather than equal to its.here is the result and code:
![image](https://cloud.githubusercontent.com/assets/9473445/22683630/d8223466-ed53-11e6-90ac-cdd8bac7b4fa.png)

```swift
       ring1.animationStyle = kCAMediaTimingFunctionLinear
        ring1.fontSize = 20
        ring1.fontColor = UIColor.yellow
        ring1.maxValue = 10
        ring1.viewStyle = 2
        ring1.innerRingColor = UIColor.yellow
        ring1.setProgress(value: 9, animationDuration: 5, completion: nil)
```
here is I want it to be that:
![image](https://cloud.githubusercontent.com/assets/9473445/22683646/e83f1da0-ed53-11e6-9fd3-13ff3fc8aa7b.png)
Should I set the inner circle width to equal the outer circle width?? I tried that ring1.innerRingWidth = ring1.outerRingWidth, it can not achievement my thinking, Hope you can help me, thanks!

**Comment by luispadron** [comment]
That's weird, just tried this and it seems to be working fine

If I do this:

```swift
override func viewDidLoad() {
    super.viewDidLoad()
        
    ring.animationStyle = kCAMediaTimingFunctionLinear
    ring.fontSize = 20
    ring.fontColor = UIColor.yellow
    ring.maxValue = 10
    ring.viewStyle = 2
    ring.innerRingColor = UIColor.yellow
}
```

I get this: 

<img width="372" alt="screen shot 2017-02-07 at 11 47 25 am" src="https://cloud.githubusercontent.com/assets/13840545/22701456/ac8a1012-ed2b-11e6-83fa-f16da284e3ef.png">


If you want them to be the same width you can add what you said above

```swift
ring.innerRingWidth = ring.outerRingWidth
```

And I get this: 

<img width="372" alt="screen shot 2017-02-07 at 11 46 57 am" src="https://cloud.githubusercontent.com/assets/13840545/22701504/cbdc3a76-ed2b-11e6-9eef-13db2e32d8c8.png">


Are you on the latest version? 
I'm not getting the issues you are seeing, is this view being presented inside a view controller or some other type of view? If you'd like help you could post the example project here, or the code. If you prefer to keep the project private you could send it to me in an email to [luis@luispadron.com](mailto:luis@luispadron.com)

**Comment by NancyZY** [comment]
Thanks for your answer, I finished it after update the library.

**Comment by luispadron** [comment]
Cool glad that fixed it!
