### ISSUE TITLE
Bordered display style does not support circles that aren't full

### ISSUE THREAD

**Issue by jessemx109** [luispadron/UICircularProgressRing#133]
## Bug Report

:warning: **Your issue will be closed if these are not filled out**. :warning:

#### Version

3.3.2

#### Overview of what you tried to do

Use Bordered ring style with fullCircle set to false, startAngle set to 180 and endAngle set to 360

#### What is the expected outcome?

Border should display correctly around the half circle drawn

#### What is the actual outcome?

Border tried to draw a full circle that filled the space of the half circle. Border did not line up with the ring being drawn

#### Post sample code or example here

*If sample code can't be provided because it's too long, please provide a small example project,
where I can test, if you cannot provide either. There is not much I can do.*

```swift
        let ring = UICircularProgressRing()
        ring.fullCircle = false
        ring.startAngle = 180
       ring.endAngle = 360
       ring.ringStyle = .bordered
//Draw ring
```
#### Have you tried fixing this yourself?

This project is open source, and I'm a student with very minimal amount of time.
Please give an attempt at fixing the issue first before creating a bug report.
This saves everyone time and benefits anyone who uses the library.
Pull requests are welcome!

**Comment by luispadron** [comment]
Seems like the border is just being drawn as a full circle then?

Will look into this when I get a chance, thanks.
