### ISSUE TITLE
Xcode error 'failed to render and update auto layout status' but app does run.

### ISSUE THREAD

**Issue by RaoulNL** [luispadron/UICircularProgressRing#135]
Hi Luis,
I'm using your library (version 2.1.0) with Xcode 9.4.1 in a sample project in which the deployment target has been set to iOS 11.4. After installing Cocoapods says this message:

> Automatically assigning platform ios with version 9.3 on target CircularAnimation because no platform was specified. Please specify a platform for this target in your Podfile.

As soon as I set the class of a UIView to UICircularProgressRingView I get the same error in Xcode as kudzaiTnexus described. Is this still a problem at Cocoapods? (b.t.w. I use Cocoapods version 1.5.3)

However the project complies and runs perfectly. This issue is similar as described in issue #90 
Could you look into this?

Regards, Raoul

**Comment by luispadron** [comment]
Yes this is a cocoa pods issue as described in #90. I can't fix this since I don't maintain the CocoPods library, however, from what I understand they have a fix for this and it should be out soon.
