### ISSUE TITLE
CAMediaTimingFunctionName issue

### ISSUE THREAD

**Issue by goktugaral** [luispadron/UICircularProgressRing#138]
## Bug Report

Use of undeclared type 'CAMediaTimingFunctionName'

#### Version

4.0.0

#### Overview of what you tried to do

I was using old version of UICircularProgressRing. I did "pod update" and I compiled my project then 
an error has been occurred.

<img width="325" alt="screen shot 2018-09-17 at 11 19 12" src="https://user-images.githubusercontent.com/8982519/45612435-9b071600-ba6b-11e8-903d-e7536ec0e7ee.png">

### What did I tried?

I did downgrade to version 3.3.2 and it worked.

####
xCode 9.4.1
Swift 4.1

**Comment by christianharrison** [comment]
I'm experiencing the same issue- however this is my first time using it, and I'm pretty new to programming. How would I go about downgrading? Can I find previous versions on Github?

**Comment by christianharrison** [comment]
I cleaned my project and it's now working again.

**Comment by Sensiblemnd** [comment]
same issue here after Pod Update

**Comment by luispadron** [comment]
The project has been updated to Swift 4.2. Either keep the old version, or update and migrate to use new Xcode.

**Comment by Akshay-bcat** [comment]
Experiencing same issue with Xcode 11 Swift 5.0
