### ISSUE TITLE
How get current ring value?

### ISSUE THREAD

**Issue by SeRG1k17** [luispadron/UICircularProgressRing#14]
My view contains a button, after buttonTap I want to speed up the ring starting now like as

ring.setProgress(value: ring.currentValue, animationDuration: 5 , completion: nil)

**Comment by luispadron** [comment]
Confused about what you mean by this, could you elaborate a bit more?

Why would you want to set the progress of the ring to its current value, that wouldn't animate or cause any changes. 

To get the current value you just need to do `ring.value`

**Comment by SeRG1k17** [comment]
after click ring.value return 0.0 all time
![2017-02-14 23 28 17](https://cloud.githubusercontent.com/assets/13317173/22947761/4fb003c8-f30d-11e6-9cba-ee1290570ecf.png)
![2017-02-14 23 29 07](https://cloud.githubusercontent.com/assets/13317173/22947804/66b7d276-f30d-11e6-976a-eddb70142563.png)

**Comment by SeRG1k17** [comment]
i found solution, but not good

`var startTime:TimeInterval!`
//...
```
func setRingProgress(withDuration duration: TimeInterval, andValue value: CGFloat) {
        startTime = Date.timeIntervalSinceReferenceDate
        
        ring.value = value
        ring.setProgress(value: 0, animationDuration: duration, completion: nil)
    }
```
//...
//in button Action
```
        let elapsedTime = Date.timeIntervalSinceReferenceDate - startTime
        let newValue = ringDuration - elapsedTime
        let newDuration = (newValue + ringDuration) / ringDuration
        setRingProgress(withDuration: TimeInterval(newDuration), andValue: CGFloat(newValue))
```

**Comment by luispadron** [comment]
The reason you're getting the wrong value is because you are not using the completion handler...

Animations take time, unless you use a duration of 0 which will update it instantly. In order to find value AFTER animation you must get the ring value in the completion handler.

Here is an example:

    override func viewDidLoad() {
        super.viewDidLoad()
        print("Value before: \(ring.value)") // OUTPUT: "Value before: 0.0"
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        ring.setProgress(value: 9, animationDuration: 5) {
            print("Value after: \(self.ring.value)") // OUTPUT: "Value after: 9.0"
        }
    }

There is no need to use time intervals or logic for that. Just set a completion handler, this will get called when the ring is done animating. 

Please look at the [documentation](http://htmlpreview.github.io/?https://github.com/luispadron/UICircularProgressRing/blob/master/docs/index.html) if you have some more questions or let me know if this helps.

**Comment by SeRG1k17** [comment]
Your example does not include pressing the button.
Please see this, sorry for the bad quality.
https://vimeo.com/204075530

**Comment by luispadron** [comment]
I'm not going to write a full example as I don't have the time currently. But this should work as intended. If you're using an IBAction then you would call the set progress in there.

If you would like more help, please either post your project on here or send me an email with the project if you prefer to keep it private and I can take a look at it.

**Comment by SeRG1k17** [comment]
[test](https://github.com/SeRG1k17/ProgressTest)

**Comment by luispadron** [comment]
I see what you're saying now. You would like to get the value and have it be an updating value as the progress ring is animating.

This, however, is not a feature that was originally expected to be needed, so was never added and is not currently something I have the time to add. When I get a chance to look at it again I may be able to add this. However, you could also fork the repo and send a pull request and I'll gladly accept any changes after review!

**Comment by luispadron** [comment]
Got around to fixing this in version 1.3.0. 

You can now access the current value by using `currentValue`. This will give you the exact value when called, even if ring is animating.

Thanks for posting your issue!

Read the upated docs [here](http://htmlpreview.github.io/?https://github.com/luispadron/UICircularProgressRing/blob/master/docs/index.html)

**Comment by SeRG1k17** [comment]
Nice work dude!

**Comment by NickAwesome** [comment]
![screen shot 2017-05-20 at 6 04 06 pm](https://cloud.githubusercontent.com/assets/28800124/26274872/dd7d0214-3d86-11e7-86eb-83258f03defb.png)
hi , currentvalue doesnt seems like working

**Comment by luispadron** [comment]
@NickAwesome, please read the error message Xcode is giving you. `currentValue` is a get only property, thus cannot be set. 

If you want to set the value then call 

```swift
.setProgress(value:duration)
```
