### ISSUE TITLE
Issue with Carthage installation

### ISSUE THREAD

**Issue by scrapp3rz** [luispadron/UICircularProgressRing#146]
:warning: **This issue will be closed if the required information is not filled** :warning:
Hi, 
I have an issue installing with Carthage, it seems that the Swift version is incompatible, do you know when you'll make your next update?
Or do you have some clue to install instead of this problem?

Thanks

![capture d ecran 2018-10-03 a 12 41 15](https://user-images.githubusercontent.com/28725862/46405906-060e4900-c70a-11e8-84d5-c1e577e4e4bf.png)

_If it's a question about something that is happening within your code base, either post a small amount of code, or post an example project where I can try to assist.
Make sure to communicate back and keep issue updated or it will be closed_

## Version

- Version = current

## Details

- Has the question been answered [here](https://github.com/luispadron/UICircularProgressRing/issues?utf8=✓&q=label%3Aquestion) before?
  - not yet
- Please provide as much detail as possible below
  - Since I'm using Xcode 10.1 i've issues when installing with Carthage. I've tried with CocoaPods, same issue.

**Comment by luispadron** [comment]
Sorry are you using Xcode 10.1? Is that a beta version? I'm on Xcode 10 but don't have any pending updates.

**Comment by luispadron** [comment]
Could you try it now? I updated my Carthage and archived a new version of 4.0.0. If that doesn't work, see if the 4.1.0 version works.

**Comment by scrapp3rz** [comment]
Yes, it works great again with Xcode10, i've tried in 10.1 and it's fine too!
Thank your for you quick answer!
