### ISSUE TITLE
Type 'CAMediaTimingFunctionName' (aka 'NSString') has no member 'easeInEaseOut'

### ISSUE THREAD

**Issue by raulastu** [luispadron/UICircularProgressRing#147]
## Bug Report

line 835

class UICircularProgressRing
Type 'CAMediaTimingFunctionName' (aka 'NSString') has no member 'easeInEaseOut'

:warning: **Your issue will be closed if these are not filled out**. :warning:

#### Version

4.0.0
xcode Version 10.0 (10A255)

#### Overview of what you tried to do

make it work. it used to work before

#### What is the expected outcome?

to work

#### What is the actual outcome?

it doesnt compile

#### Post sample code or example here

*If sample code can't be provided because it's too long, please provide a small example project,
where I can test, if you cannot provide either. There is not much I can do.*

```swift
ANSWER HERE
```
#### Have you tried fixing this yourself?
yes this is the solution I tried, please update

    @objc open var animationTimingFunction: CAMediaTimingFunctionName = kCAMediaTimingFunctionEaseInEaseOut as CAMediaTimingFunctionName {
        didSet {
            ringLayer.animationTimingFunction = animationTimingFunction
        }
    }

This project is open source, and I'm a student with very minimal amount of time.
Please give an attempt at fixing the issue first before creating a bug report.
This saves everyone time and benefits anyone who uses the library.
Pull requests are welcome!

**Comment by luispadron** [comment]
Don’t really appreciate the snarky comments. They’re uninformative and don’t help solve anything. 

Rewrite your issue to explain the problem better.

**Comment by luispadron** [comment]
Your issue has to do with you using an outdated Swift version. Version 4.0.0+ of this project requires the latest Swift 4.2.

Please read the CHANGELOG and Documentation before posting an issue.
