### ISSUE TITLE
Animate doesn't work

### ISSUE THREAD

**Issue by reshadf** [luispadron/UICircularProgressRing#15]
I have the following setup. But the animation is not working it just appears on the screen. Any clue on what I am doing wrong? 

    let profileProgressView: UICircularProgressRingView = {
       
        let view = UICircularProgressRingView(frame: CGRect(x: 0, y: 0, width: 124, height: 124))
        view.maxValue = 100
        view.outerRingColor = UIColor.white
        view.innerRingColor = UIColor.white
        view.viewStyle = 2
        view.startAngle = 90
        view.outerRingCapStyle = 2
        view.outerRingWidth = 8
        view.shouldShowValueText = false
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
        
    }()

    func setConstraints() {
        profileProgressView.topAnchor.constraint(equalTo: profileBackgroundView.topAnchor, constant: 8).isActive = true
        profileProgressView.centerXAnchor.constraint(equalTo: profileBackgroundView.centerXAnchor).isActive = true
        profileProgressView.widthAnchor.constraint(equalToConstant: 124).isActive = true
        profileProgressView.heightAnchor.constraint(equalToConstant: 124).isActive = true
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        delay(2.5, completion: {
            self.profileProgressView.setProgress(value: 60, animationDuration: 5, completion: nil)
        })
    }
    
    func delay(_ seconds: Double, completion:@escaping ()->()) {
        let popTime = DispatchTime.now() + Double(Int64( Double(NSEC_PER_SEC) * seconds )) / Double(NSEC_PER_SEC)
        
        DispatchQueue.main.asyncAfter(deadline: popTime) {
            completion()
        }
    }

**Comment by luispadron** [comment]
Why was this closed, did you fix the issue? If you don't mind, quickly posting a solution in case anyone else happens to have the same problem.

Thanks!

**Comment by reshadf** [comment]
Im so sorry, after I posted this I found out I gave the same color to both inner and outer circle, i assumed, since the circle wasnt a full circle because I gave a max value that it would close at 100% but apparently it doesnt work like that. So what I saw with my code was a circle with a 100 value and a inner circle that animates but you didnt see it because theybhad the same color

**Comment by luispadron** [comment]
Haha no problem, glad it's working! 
Thanks for updating the issue
