### ISSUE TITLE
 Implement a countdown timer

### ISSUE THREAD

**Issue by AntoGeekz** [luispadron/UICircularProgressRing#150]
Hey,

Is it possible to implement a countdown timer with this lib? I tried to implement it but I have some troubles to find the best way to do it. 

Do you have a example maybe? Or just to tell me what I have to use to achieve this goal?

Thanks, and nice job for this lib :)

**Comment by luispadron** [comment]
This isn't the best place to ask this, I recommend StackOverFlow for implementation related questions.

But yes this is possible as many users have done this before.
I recommend looking at the documentation for this library and implementing it using some sort of timer. 
Look at docs for this lib [here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularProgressRing.html)
Check out Apple API for Timer [here](https://developer.apple.com/documentation/foundation/timer)

**Comment by UzumakiAlfredo** [comment]
I have this question too.
I used it like this:
 ```
let timerRing = UICircularTimerRing()
        timerRing.startTimer(to: removeCellsAnimationTime) { state in
            switch state {
            case .finished:
                print("finished")
            case .continued(let time):
                print("continued")
            default: break
            }
        }
```

but '.continued(let time):' never get called !

**Comment by luispadron** [comment]
@UzumakiAlfredo the original issue was created before `UICircularTimerRing` so these questions are not related. If you have a bug to report please file a new issue and i’ll take a look at it.

**Comment by UzumakiAlfredo** [comment]
@luispadron are you saying not calling the continued state is caused by another none relative problem?
