### ISSUE TITLE
Type 'CAMediaTimingFunctionName' (aka 'NSString') has no member 'easeInEaseOut'

### ISSUE THREAD

**Issue by julestburt** [luispadron/UICircularProgressRing#156]
I'm trying to build this pod with Xcode 10? Any help would be appreciated...

UICircularProgressRing.swift line 838...

**Comment by luispadron** [comment]
follow posting guidelines, this has been asked several times [here](https://github.com/luispadron/UICircularProgressRing/issues?q=is%3Aissue+is%3Aclosed)
