### ISSUE TITLE
Error in example playground file

### ISSUE THREAD

**Issue by zhanswift** [luispadron/UICircularProgressRing#157]
I have error in playground file `UICircularProgressRingExample.playground`

>/Users/UICircularProgressRing-master/Example/UICircularProgressRingExample.playground/Sources/UICircularProgressRing.swift:757:45: Cannot convert value of type 'CAMediaTimingFunctionName' to specified type 'String'

Code
```
@objc open var animationStyle: String = kCAMediaTimingFunctionEaseIn {
        didSet {
            ringLayer.animationStyle = animationStyle
        }
    }
```

P.S. Use Xcode 10

**Comment by luispadron** [comment]
Yah the example project has yet to be updated to the latest version. The lib itself is updated for Xcode 10 and Swift 4.2 though
