### ISSUE TITLE
Four Quarters Gradient Progress Ring

### ISSUE THREAD

**Issue by HadiYaac** [luispadron/UICircularProgressRing#158]
Hello,

Thanks for this great repository 👍, I was just wondering if I can make the Progress Ring to accept 4 different colors and apply gradient on these colors equally, like each quarter presents a color respectively from the array provided?

Currently when an array with 4 colors passed in *circularProgress.gradientColors* with a given *circularProgress.gradientStartPosition* it shows the gradient colors but all 4 colors are compressed to show in the available area read from the value, which is logical. But I need each quarter to present a specific color from this array. Like if the value is still less than 25% I don't need any other color to show.

Plus, by default it is showing the 4 colors from the start point to 180 degree and then revert the array and complete the circle which is weird! like if I have **[a,b,c,d]** array of UIColors. It shows 
**a,b,c,d from 0 -> 180 - d,c,b,a from 181 -> 360** 

Thanks again.

**Comment by luispadron** [comment]
The reason the gradient might look odd is because it's drawn using a square gradient and then masked over by the circular ring.

Could you post an image of what you're experiencing and what you want?
It's hard to think about this without a visual image

**Comment by HadiYaac** [comment]
Hello,
This is a screenshot from what I am experiencing when providing 4 colors in gradient array.
What I need is filling the circle with 4 equal quarters each one representing a color from that array.

![simulator screen shot - iphone x - 2018-12-05 at 12 37 31](https://user-images.githubusercontent.com/20638321/49508208-cb03cf80-f88a-11e8-9aa5-7a8db39fc2a7.png)

**Comment by HadiYaac** [comment]
@luispadron please reply

**Comment by luispadron** [comment]
Hey, sorry it’s finals week at school so I won’t be able to look at this for a bit. I’ll look as soon as I get a chance

**Comment by asad-khan92** [comment]
Any update on this, I'm too facing this issue
