### ISSUE TITLE
Abort trap: 6 when Archiving

### ISSUE THREAD

**Issue by hoang-ei** [luispadron/UICircularProgressRing#160]
## Bug Report

3.	While deserializing SIL vtable for 'UICircularProgressRing' in module 'UICircularProgressRing'
error: Abort trap: 6

#### Version

4.1.0

#### Overview of what you tried to do

When running on simulator it works ok but as soon as I choose to archive it throws abort trap: 6

**Comment by luispadron** [comment]
I’m going to need more than this to be able to debug

**Comment by hoang-ei** [comment]
After migrating project from 4.1 to 4.2 and setting Swift language version to 4.2 it is archiving ok.
