### ISSUE TITLE
RTL support?

### ISSUE THREAD

**Issue by BaluNaik** [luispadron/UICircularProgressRing#162]
:warning: **This issue will be closed if the required information is not filled** :warning:

_If it's a question about something that is happening within your code base, either post a small amount of code, or post an example project where I can try to assist.
Make sure to communicate back and keep issue updated or it will be closed_

## Version

- Version = 3.3.2

## Details

- Has the question been answered [here](https://github.com/luispadron/UICircularProgressRing/issues?utf8=✓&q=label%3Aquestion) before?
  - NO
- Please provide as much detail as possible below
  - it's working fine for english, but i want graph is reverse order for arabic.

**Comment by luispadron** [comment]
Have you read the docs? There is support for this already.
