### ISSUE TITLE
Not rendering in Storyboard

### ISSUE THREAD

**Issue by Kondamon** [luispadron/UICircularProgressRing#165]
:warning: **This issue will be closed if the required information is not filled** :warning:

_If it's a question about something that is happening within your code base, either post a small amount of code, or post an example project where I can try to assist.
Make sure to communicate back and keep issue updated or it will be closed_

## Version

- Version = 5.1.0

## Details

- Has the question been answered [here](https://github.com/luispadron/UICircularProgressRing/issues?utf8=✓&q=label%3Aquestion) before?
  - Yes and No, there was an answer related to CocoaPods but I'm using Carthage
- Please provide as much detail as possible below
  - I have added the framework via Carthage to a new empty project. 
  - In the Storyboard I added a new View and set the custom class and the module to UICircularProgressRing.
  - When I run the project I can see the bar in the simulator. In the storyboard nothing is shown.

**Comment by luispadron** [comment]
Hi there,

From the readme: "Important: Interface builder support with Carthage is either broken or extremely limited"

Carthage does not support `@IBDesignable`, if you'd like storyboard support you need to use cocoa pods.
