### ISSUE TITLE
Gradient circle with grey

### ISSUE THREAD

**Issue by dbarrett0815** [luispadron/UICircularProgressRing#166]
## Version

- Version = 5.1.0

## Details
Thanks for the awesome library. Im trying to acheive the following ring below but with a gradient style for the ring on top. If i choose a gradient style for the ring, i no longer have the grey track color.
![image](https://user-images.githubusercontent.com/9472804/52833329-3e576800-30aa-11e9-931c-6d3ab3855b09.png)

**Comment by JesusMartinAlonso** [comment]
Hi @dbarrett0815. I have faced the same issue today. This is possible by setting the color of the inner ring. This is the code I use to customize the progress ring:
```
fileprivate func  configureCircularProgress() {
        circularProgressView.ringStyle = .gradient
        circularProgressView.startAngle = 270.0
        circularProgressView.endAngle = 269.0
        circularProgressView.outerRingWidth = 20.0
        circularProgressView.innerRingWidth = 20.0
        circularProgressView.innerRingColor = UIColor.gray
        circularProgressView.gradientColors = [StatusStyle.gradientColorsHighState.startColor, StatusStyle.gradientColorsHighState.endColor]
        circularProgressView.setNeedsDisplay()
        circularProgressView.startProgress(to: 80.0, duration: 1.0)
        
    }
```

**Comment by luispadron** [comment]
Hi there, the reason I believe you don't see the outer ring when in gradient style is due to a mask. I wasn't the one who added this feature so not 100% sure, but there is a layer mask that is added. Try the above solution and let me know if it worked!

**Comment by JesusMartinAlonso** [comment]
Hi again @dbarrett0815 @luispadron 
Sorry, but the solution I posted above is not right. The gradient is set to the `innerRing` so the solution is to set the `color` and `width` of the outer ring. This is the updated code:

```
fileprivate func  configureCircularProgress() {
        circularProgressView.ringStyle = .gradient
        circularProgressView.showsValueKnob = false
        circularProgressView.startAngle = 270.0
        circularProgressView.endAngle = 269.0
        circularProgressView.outerRingWidth = 20.0
        circularProgressView.innerRingWidth = 20.0
        circularProgressView.outerRingColor = UIColor(red: 238.0 / 255.0, green: 238.0 / 255.0, blue: 238.0 / 255.0, alpha: 1.0)
        circularProgressView.gradientColors = [StatusStyle.gradientColorsHighState.startColor, StatusStyle.gradientColorsHighState.endColor]
        circularProgressView.shouldShowValueText = false
        circularProgressView.startProgress(to: 80.0, duration: 1.0)
    }
```

<img width="163" alt="screen shot 2019-02-21 at 08 15 25" src="https://user-images.githubusercontent.com/9574791/53150496-f906cf00-35b0-11e9-87c6-cf1937515d9b.png">

Hope this help!

**Comment by dbarrett0815** [comment]
Hi @JesusMartinAlonso. Thanks for the code snippet. There seems to have been some API changes recently so some of the properties have changed a bit. Primary you have to supply a gradienOption for a gradient style. And with that style, the ring with the gradient is placed as an inner ring. 
    
        let gradientOptions = UICircularGradientOptions(startPosition: .topLeft, endPosition: .topRight, colors: [UIColor(hex: "#aa076b"), UIColor(hex: "#61045f")], colorLocations: [0.1, 1.0])

        progressView.startAngle = 270.0
        progressView.endAngle = 269.0
        progressView.outerRingWidth = 20.0
        progressView.innerRingWidth = 20.0
        progressView.outerRingColor = UIColor(red: 238.0 / 255.0, green: 238.0 / 255.0, blue: 238.0 / 255.0, alpha: 1.0)
        progressView.style = .gradient(options: gradientOptions)
        progressView.shouldShowValueText = false
        progressView.startProgress(to: 80.0, duration: 1.0)

The above code produces the picture below 
![screen shot 2019-02-21 at 9 03 08 am](https://user-images.githubusercontent.com/9472804/53174641-4d617d00-35b8-11e9-824a-960a5f7fa0a0.png)

        let gradientOptions = UICircularGradientOptions(startPosition: .topLeft, endPosition: .topRight, colors: [UIColor(hex: "#aa076b"), UIColor(hex: "#61045f")], colorLocations: [0.1, 1.0])

        progressView.startAngle = 270.0
        progressView.endAngle = 269.0
        progressView.outerRingWidth = 0
        progressView.innerRingWidth = 20.0
        progressView.outerRingColor = UIColor(red: 238.0 / 255.0, green: 238.0 / 255.0, blue: 238.0 / 255.0, alpha: 1.0)
        progressView.style = .gradient(options: gradientOptions)
        progressView.shouldShowValueText = false
        progressView.startProgress(to: 80.0, duration: 1.0)

And the same code above but specifying a outerWidth with of 0 produces only the inner ring still with no track. 
![screen shot 2019-02-21 at 9 02 32 am](https://user-images.githubusercontent.com/9472804/53174724-7c77ee80-35b8-11e9-8135-935ed44ad77c.png)

Any ideas? Ill take a deeper look to see how to acheive the result with the recent updates to the API and get back here in the mean time any suggestions would be appreciated

**Comment by luispadron** [comment]
Oh I think i know what the problem is. When i updated the API I must have broken style support with gradient and outer ring options since you can only pick one style. The fix is rather easy but it’s going to require moving the gradient style option to its own property. When I have some free time i’ll try to get this fixed, sorry!

**Comment by dbarrett0815** [comment]
@luispadron Thanks for the reply! I figured something must have changed because I was able to get it a few weeks ago. Looking forward to the fix whenever that is.

**Comment by luispadron** [comment]
@dbarrett0815, checkout [version 6.0.0](https://github.com/luispadron/UICircularProgressRing/releases/tag/v6.0.0), should fix this issue!

**Comment by dbarrett0815** [comment]
@luispadron Thanks everything seems to be working now!
