### ISSUE TITLE
Dashed inner ring?

### ISSUE THREAD

**Issue by Neilfau** [luispadron/UICircularProgressRing#167]
:warning: **This issue will be closed if the required information is not filled** :warning:

_If it's a question about something that is happening within your code base, either post a small amount of code, or post an example project where I can try to assist.
Make sure to communicate back and keep issue updated or it will be closed_

## Version

- Version = 5.1.0

## Details

- Has the question been answered [here](https://github.com/luispadron/UICircularProgressRing/issues?utf8=✓&q=label%3Aquestion) before?
  - Not that I can see.
- Please provide as much detail as possible below
  - Is it possible to customise the inner progress ring? I want to have dashed progress for both the inner and outer rings. I tried setting the line dash for the bezier path of the inner ring but that doesn't seem to work.

**Comment by luispadron** [comment]
Hi there, no this is currently not possible. You could add it by modifying the layer class and how it draws the ring, but there are no plans right now to add this.
