### ISSUE TITLE
How to implement as a timer?

### ISSUE THREAD

**Issue by f15handch1p5** [luispadron/UICircularProgressRing#17]
I want to implement a timer component into my app. I'm just confused on how to go about doing it with this library.

**Comment by luispadron** [comment]
Not sure what you are asking here, please go into more detail.
 
Have you read the documentation? Please read this [here](http://htmlpreview.github.io/?https://github.com/luispadron/UICircularProgressRing/blob/master/docs/index.html) if you haven't yet done so.

**Comment by luispadron** [comment]
Closing since never replied.
