### ISSUE TITLE
How can I set valueIndicator?

### ISSUE THREAD

**Issue by yaya1026** [luispadron/UICircularProgressRing#173]
:warning: **This issue will be closed if the required information is not filled** :warning:

_If it's a question about something that is happening within your code base, either post a small amount of code, or post an example project where I can try to assist.
Make sure to communicate back and keep issue updated or it will be closed_

## Version

- Version = 6.0.1

## Details

- Has the question been answered [here](https://github.com/luispadron/UICircularProgressRing/issues?utf8=✓&q=label%3Aquestion) before?
  - yes
- Please provide as much detail as possible below

Thanks for a nice library!
I use UICircularProgressRing and I want to change valueIndicator(% -> days).
I've read doc but i couldn't. How can I set this value?
The following error message appears.
![2019-02-27 12 40 01](https://user-images.githubusercontent.com/23512935/53464488-c74ca700-3a8d-11e9-8c27-8b30cb2eaf27.png)
I look forward to your reply!(Sorry for my poor English)

**Comment by luispadron** [comment]
Please read changelog and documentation, its clearly stated in those as well as Xcode warning you.

- [Docs](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Structs/UICircularProgressRingFormatter.html)
- [Changelog](https://github.com/luispadron/UICircularProgressRing/blob/master/CHANGELOG.md)
