### ISSUE TITLE
Not animating after first animating in TableViewCell

### ISSUE THREAD

**Issue by zhanswift** [luispadron/UICircularProgressRing#176]
## Version

- Version = 4.1.0

## Details

ProgressUIView's I put on TableViewCell of DetailViewController. 
They start animation when tapped download button.
Animation work at first time.
But when I close DetailViewController and open again and start download progressUIView appear but not animating.

**Comment by luispadron** [comment]
Not exactly sure I understand what's going on here, please provide more information or sample.
