### ISSUE TITLE
How to totally customize the center label?

### ISSUE THREAD

**Issue by yybot1** [luispadron/UICircularProgressRing#177]
It seems you cannot directly edit the center label, but has to use UICircluarRingValueFormatter, but how to do the following?

1. when value reaches maxValue, display "Done"
2. when value is above maxValue, format and display the value, not maxValue.

I think the center label should be editable directly and not has to related to the "value".

Version 6.0.2

**Comment by yybot1** [comment]
Well, I think I found workarounds to do what I want. 

1. Set value and maxValue to a magic number, like 99999, if value is 99999, then display "Done"
2. if value is above maxValue, set maxValue equal to value.

But I still want to know if there are more elegant methods.

**Comment by luispadron** [comment]
Hi,

I see what you're trying to do and, you're correct this is not possible. The label of the ring is tied to the value of the ring, and I don't see this changing as this is the most common use case.

I believe a more elegant solution to your request is to simply not display the label of the ring. You can then overlay your own `UILabel` over the center of the ring and do anything custom you need using either the delegate for the ring or the completion handlers.

**Comment by luispadron** [comment]
I'm going to close this issue as I feel the solution I described above is the best way to go about doing this. Thanks for using the library! Feel free to ask any more questions you may have here.
