### ISSUE TITLE
The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by mspeed101** [luispadron/UICircularProgressRing#178]
## Bug Report
XCode Version 10.2 (10E125)
UICircularRingLayer.swift
line : 247
The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions  

:warning: **Your issue will be closed if these are not filled out**. :warning:

#### Version 5.1.0 -> last version (6.0.2)

ANSWER HERE

#### Overview of what you tried to do

ANSWER HERE

#### What is the expected outcome?

ANSWER HERE

#### What is the actual outcome?

ANSWER HERE

#### Post sample code or example here

*If sample code can't be provided because it's too long, please provide a small example project,
where I can test, if you cannot provide either. There is not much I can do.*

let offSet = max(ring.outerRingWidth, ring.innerRingWidth) / 2 + ((valueKnobStyle?.size ?? 0) / 4) + (borderWidth * 2)

```swift
ANSWER HERE
```
#### Have you tried fixing this yourself?

let a = max(ring.outerRingWidth, ring.innerRingWidth) / 2
            let b = (valueKnobStyle?.size ?? 0) / 4
            let c = borderWidth * 2
            let offSet = a + b + c

This project is open source, and I'm a student with very minimal amount of time.
Please give an attempt at fixing the issue first before creating a bug report.
This saves everyone time and benefits anyone who uses the library.
Pull requests are welcome!

**Comment by darecki** [comment]
Fixed in https://github.com/luispadron/UICircularProgressRing/pull/179 but Travis doesn't accept Swift 5 as of now.

**Comment by luispadron** [comment]
Now out in version 6.1.0
