### ISSUE TITLE
Silence 'not drawing value label' debug log

### ISSUE THREAD

**Issue by lrholmes** [luispadron/UICircularProgressRing#18]
The debugging area becomes nearly unusable when `shouldShowValueText = false` because it is constantly printing `Not drawing value label because shouldShowValueText = false`.

It'd be nice to have the option to silence this in some way, in the meantime I'm having to just display the undesired label during development.

**Comment by luispadron** [comment]
woops, sorry about that, completely removed this statements as they're not needed

Feel free to update to [Version 1.2.2](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.2.2)
