### ISSUE TITLE
Change progress ring value text

### ISSUE THREAD

**Issue by asafetech1** [luispadron/UICircularProgressRing#180]
Hi,

I using your library for displaying progress of my company apps, but I having trouble of how to change progress value text inside progress ring. I want to change default label '%' to some label. How I can do that? Thank you and awesome library btw.

Best regards,
Nyoman Sandyasa

**Comment by luispadron** [comment]
Hi please take a look at #177

**Comment by luispadron** [comment]
And also the documentation [here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularProgressRing.html)

**Comment by asafetech1** [comment]
Hi,

Thank you for the response, and yes I have read the log and now I have know how to change the default value '%' with UICircularProgressRingFormatter. Thank you so much and the library really helped a lot. 


Cheers,
Nyoman Sandyasa
