### ISSUE TITLE
Add some demo project

### ISSUE THREAD

**Issue by sulaiman-mlbd** [luispadron/UICircularProgressRing#181]
Hello, 
First of all, thank you for your project which is saving me from pain. You example playground file don't run on my machine and i think that one is not sufficient. I suggest you to add some demo project like the given image on your readme file. It would be helpful for us. 
Thank you

**Comment by luispadron** [comment]
Example projects take way too much time to write and maintain which is why i have gone against one. If you’d like to make one and maintain, PRs are welcome. Otherwise, this is why i spend so much time on the documentation. Thanks!
