### ISSUE TITLE
Xcode 10.2 error: The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by nylemusgrave** [luispadron/UICircularProgressRing#183]
Upon trying to build with Xcode 10.2 I get compiler error.

The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

On line 270 of UICircularRingLayer.swift

**Comment by luispadron** [comment]
Have you updated to version 6.1? This was fixed in that release.

**Comment by luispadron** [comment]
Take a look at #179
