### ISSUE TITLE
Allow setting UICircularTimerRing start time

### ISSUE THREAD

**Issue by joeljfischer** [luispadron/UICircularProgressRing#184]
**Describe the solution you'd like**
I'd like to be able to start UICircularTimerRing at a value other than 0, like I can with UICircularProgressRing, but I currently can't (e.g. if a timer was in progress, but the user navigated away, and then navigated back).

**Describe alternatives you've considered**
My closest alternative currently is to use UICircularProgressRing with a custom UICircularRingValueFormatter that formats based on a passed total duration and count down instead of up. It's hacky, but it should work.

**Comment by luispadron** [comment]
This shouldn't be too hard to implement. I'm a bit busy with school right now, so I'll try and get this done when I get a chance, thanks for the feedback!
