### ISSUE TITLE
Ring does not render in storyboard

### ISSUE THREAD

**Issue by thejbix** [luispadron/UICircularProgressRing#187]
## Bug Report

After updating to version 6.1, I can't set the custom class/module to UICircularProgressRing.  The framework is linked and I am still able to create UICircularProgressRings programmatically and they work correctly when running the app. 

This is a pretty great framework and easy to use.  Thanks for any advice/help you can give.

#### Version
UICircularProgressRing 6.1
Xcode 10.2
Swift 5.0

#### Overview of what you tried to do

I've cleaned and rebuilt the project.  Restarted Xcode.  Manually enter UICircularProgressRing into the class and module components of Custom Class window in the story board editor.  

#### What is the expected outcome?

UICircularProgressRing should be selectable and the view should reflect these changes and display a customizable UICircularProgressRing in the story board editor.

#### What is the actual outcome?

View remains an empty UIView

#### Post sample code or example here

*If sample code can't be provided because it's too long, please provide a small example project,
where I can test, if you cannot provide either. There is not much I can do.*

https://github.com/thejbix/testCircular
Public project with one view that contains a view.  UICircularProgressRing framework in linked and embedded into the project. Verified the above problem remained after creating this simple project. 

#### Have you tried fixing this yourself?

Yes

**Comment by luispadron** [comment]
Hi, this looks similar to #90. 

This again seems like a CocoaPods issue, something I have no control over. 
If you don't think these are the same problems, feel free to follow up, otherwise we will have to wait for the CocoaPods people to fix this issue again.

**Comment by thejbix** [comment]
I am using Carthage 0.32

**Comment by luispadron** [comment]
Ah makes more sense, since I remember cocoa pods fixing this bug.
Sadly, Carthage does not support interface builder for their frameworks so there's nothing I can do here either. You can use cocoa pods if you really need the IB functionality.
