### ISSUE TITLE
Crash on UICircularRingLayer

### ISSUE THREAD

**Issue by BorisLegovic** [luispadron/UICircularProgressRing#189]
I have a crash 

 var ringLayer: UICircularRingLayer {
        // swiftlint:disable:next force_cast
        return layer as! UICircularRingLayer
    }

 Could not cast value of type 'CALayer' (0x2022f3468) to 'UICircularProgressRing.UICircularRingLayer' (0x100edb1a0).

its inside UICircularRing.swift line 336

**Comment by luispadron** [comment]
I'm going to need more information than that to help here.

**Comment by kaibadash** [comment]
I got same error after I updated to latest version.
I was able to fix it 👍 

## before
![スクリーンショット 2019-04-30 10 59 26](https://user-images.githubusercontent.com/391549/56937416-77469b00-6b37-11e9-8328-cbc7e3cbf328.png)

`UICircularProgressRingView` is old.

## after
![スクリーンショット 2019-04-30 10 59 53](https://user-images.githubusercontent.com/391549/56937428-888fa780-6b37-11e9-99f7-f14bd54bfb6e.png)

Set `UICircularProgressRing` to Class name.

**Comment by chrisvanbuskirk** [comment]
Also, if you vend 6.5 because of the SwiftUI update, make sure you Inherit Module from Target.
