### ISSUE TITLE
Stopping current animation and adding another one?

### ISSUE THREAD

**Issue by msalihkocak** [luispadron/UICircularProgressRing#19]
Hello Luis,

I am developing a speedtest app and using the framework for showing countdown for a download period. By default it is planned to be animating 10 seconds like:
`self.uploadCircle.setProgress(value: 100, animationDuration: 10.0)`
but sometimes download finishes earlier than 10 seconds. In those cases i want to stop the 10 second animation and immediately make it %100 percent. I tried several ways like:
    
    func downloadTimerInvalidator () {

        if let downReq = self.downloadRequest{
            downReq.cancel()
        }
        DispatchQueue.main.async {
            self.downloadCircle.setProgress(value: 100, animationDuration: 0.1)
        }
    }
but it didn't work. It is like ignoring this line and having the full 10 sec cycle. Any help is appreciated. Thanks.

**Comment by luispadron** [comment]
Fixed this issue in [version 1.3.0](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.3.0)

Whenever calling `setProgress(:)` while ring is animating, the current animation will be canceled and a new one will be started this should fix your issue!

Also, you can call ` self.downloadCircle.setProgress(value: 100, animationDuration: 0.1)` with an `animation duration of 0`, which will cause no animation to occur and will instantly be set to that value. 

Thanks for posting your issue, if you have any more questions feel free to update or read the docs [here](http://htmlpreview.github.io/?https://github.com/luispadron/UICircularProgressRing/blob/master/docs/index.html)
