### ISSUE TITLE
Update for Swift 5 playground

### ISSUE THREAD

**Issue by Ged2323** [luispadron/UICircularProgressRing#192]
:warning: **This issue will be closed if the required information is not filled** :warning:

Hi I have updated the code for swift 5.0
The master wouldn't compile in the latest editor.
Here are my updates.
I tried creating a pull request but new to collaborating through here.
I updated the source files in the playground.
Thanks

Yours Sincerely
Gerard Grundy
uplearned.com

[UICircularProgressRingExample.playground.zip](https://github.com/luispadron/UICircularProgressRing/files/3172744/UICircularProgressRingExample.playground.zip)

**Comment by luispadron** [comment]
Hi, thanks for this, however I've decided to remove the example playground.

While you fixed the compilation issues, the code used by the playground is actually extremely outdated and I just don't have the time to go and update the example project whenever I update the sources. This is mostly an issue with how playgrounds handle 3rd party frameworks (i.e. they don't!) and updating this every time I update the library requires too much time and effort.

Until Apple provides a better solution for dependency management in playgrounds, I'll be removing the example entirely. Thanks, sorry this code wasn't used, I still appreciate it!
