### ISSUE TITLE
Remove Text Value 

### ISSUE THREAD

**Issue by mojtaba-almoussawi** [luispadron/UICircularProgressRing#195]
## Version

- Version = 6.1.0

## Details

- Has the question been answered [here](https://github.com/luispadron/UICircularProgressRing/issues?utf8=✓&q=label%3Aquestion) before?
  - No
- Please provide as much detail as possible below
  - I need to remove the text value, so there is no value appears inside the ring, how to achieve that?

**Comment by luispadron** [comment]
Hi, have you looked at the documentation for the project?
