### ISSUE TITLE
Add support for SwiftUI

### ISSUE THREAD

**Issue by luispadron** [luispadron/UICircularProgressRing#198]
Library should support SwiftUI and integrate with new framework nicely.

**Comment by MobileMon** [comment]
It works fine as a UIViewRepresentable

**Comment by luispadron** [comment]
@MobileMon I understand. I’d still like to have a better API (more declarative) so that the library fits in better with the rest of SwiftUI

**Comment by furiosFast** [comment]
> It works fine as a UIViewRepresentable

Can you post the code?

**Comment by luispadron** [comment]
@furiosFast  The project (v7.0+) is now written using SwiftUI.
