### ISSUE TITLE
can't change indicator value formate

### ISSUE THREAD

**Issue by Ajacme** [luispadron/UICircularProgressRing#200]
:warning: **This issue will be closed if the required information is not filled** :warning:

 public init(valueIndicator: String = " GB",
                rightToLeft: Bool = false,
                showFloatingPoint: Bool = false,
                decimalPlaces: Int = 2) {
        self.valueIndicator = valueIndicator
        self.rightToLeft = rightToLeft
        self.showFloatingPoint = showFloatingPoint
        self.decimalPlaces = decimalPlaces
    }

## Version

- Version = UICircularProgressRing (6.2.0)

## Details

- Has the question been answered [here](https://github.com/luispadron/UICircularProgressRing/issues?utf8=✓&q=label%3Aquestion) before?
  - I want to remove % sign from the value indicator but I can't.
- Please provide as much detail as possible below
  - I tired with other text like GB or something then also showing default value(%) so please help me out.

Thanks

**Comment by nomimalik1769** [comment]
`var formatValue = UICircularProgressRingFormatter()
        formatValue.valueIndicator = ""
        yourView.valueFormatter = formatValue`

use it like this. I hope it helps.

**Comment by luispadron** [comment]
As @nomimalik1769 pointed out, the formatted must be reassigned as it’s a struct. This will fix your issue.
