### ISSUE TITLE
How can I make a half ring take up full space in the view?

### ISSUE THREAD

**Issue by MobileMon** [luispadron/UICircularProgressRing#205]
How can I make a half ring take up full space in the view?

The view always has space for the bottom half of the ring, but there is no bottom half

I make a half ring like this:
progressRing.fullCircle = false
progressRing.startAngle = 180
progressRing.endAngle = 360

<img width="196" alt="Screen Shot 2019-08-02 at 7 57 41 AM" src="https://user-images.githubusercontent.com/2768159/62368740-80ab1f00-b4fb-11e9-8a35-57d752415550.png">

**Comment by luispadron** [comment]
There is no way of doing this. This is just how the drawing works in the library. Not ideal, but currently there is nothing an end user can do to change this.
