### ISSUE TITLE
UICircularTimerRing - Anticlockwise progress

### ISSUE THREAD

**Issue by AlexFlyce** [luispadron/UICircularProgressRing#206]
After playing a bit with the timer component and reading the docs, I could manage to get what I wanted for my project (thanks for the very sweet work!), expect of this feature, since the progress seems to be always clockwise and apparently there's no possibility to change his direction.

Am I missing something or is this simply unavailable? Thanks

## Version

- Version = 6.2.0

![Screenshot 2019-08-05 at 16 31 22](https://user-images.githubusercontent.com/25053968/62472210-84aa9b80-b79e-11e9-8c15-85b058991d28.png)

**Comment by luispadron** [comment]
Hi there, have you tried setting the `isClockwise` property to `false`?

`UICircularTimerRing` inherits from `UICircularRing` which controls the drawing and animations of the ring. While I haven't personally tested this it should just work by setting that property. Give it a shot and follow up if it doesn't work. Check out the documentation for more information.

**Comment by AlexFlyce** [comment]
Hi Luis! Yes this is exactly what I was looking for and it works great! 
I checked the doc and it was in quite an unusual section, which is **Label** (`UICircularRing class reference` -> `Label`) so I didn't notice it.
I can close the issue then, thanks again :)
