### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by croossin** [luispadron/UICircularProgressRing#21]
Is there anyway to add padding to the view? I want it a specific size but then to be able to add padding to all sides so it "shrinks"

**Comment by luispadron** [comment]
There isn't any padding you can add to the control itself.
However, if I'm understanding you correctly you might be able to do with by enclosing the circular progress ring inside a UIView.

This way you can center the ring inside the UIView and add "padding" accordingly. 

Let me know if this makes sense or if I didn't understand what you were asking.

**Comment by luispadron** [comment]
Closing because no reply.
Reopen if you have more information to provide.

Thanks.

**Comment by jimijon** [comment]
How can one change the size of the view? I embedded it in a UIView but it doesn't fill out the enclosing UIView. Be nice to be able to set a percentage of view for width and height. I want to draw a half arc progress bar but unless I start futzing with the code it can't be done.
