### ISSUE TITLE
Little proble

### ISSUE THREAD

**Issue by baiRookie** [luispadron/UICircularProgressRing#211]
I have been using cocoaPods and I found the sample project doesn't work, so I hope the author can create a cocoaPods project,It can sovle lot of my problems.

**Comment by baiRookie** [comment]
"progressRing3.gradientOptions = UICircularRingGradientOptions.init(startPosition: .top, endPosition: .bottom, colors: [.red,.blue], colorLocations: [0,1])" , it doesn't work. How do I set the gradient.

**Comment by luispadron** [comment]
please read and follow the issue guidelines before posting an issue.

**Comment by khuong291** [comment]
@baiRookie the problem is you didn't set `innerRingWidth` property, it should be higher than 0.
