### ISSUE TITLE
cannot change font size ot type from storybord

### ISSUE THREAD

**Issue by kjoe07** [luispadron/UICircularProgressRing#215]
cannot modify in UICircularPogressRing view the size or the type of font only the font color show up in xcode 11.2
![Captura de Pantalla 2019-11-10 a la(s) 1 54 28 p  m](https://user-images.githubusercontent.com/3653060/68549026-a630aa00-03c1-11ea-97ea-66f6850cee3b.png)

**Comment by luispadron** [comment]
`UIFont` does not show up in IB  when using `IBInspectable` as such there is no longer support for that feature. Until Apple adds support for it in 3rd party libraries theres nothing I can do.
