### ISSUE TITLE
Unusual start of percentage ring

### ISSUE THREAD

**Issue by RajChanchal** [luispadron/UICircularProgressRing#22]
Most of the percentage circular rings I have seen start from vertical top, but this one doesn't. See the following pictures, for example. What is your say about it?

![circliful](https://cloud.githubusercontent.com/assets/7058465/23822026/0276941a-065d-11e7-9c6b-dba9aa36f35a.jpg)
![ck5lv](https://cloud.githubusercontent.com/assets/7058465/23822028/02b7a310-065d-11e7-986d-7aa83f9125a9.jpg)
![images](https://cloud.githubusercontent.com/assets/7058465/23822027/02b51226-065d-11e7-940c-e72d0f8da950.jpeg)
![images](https://cloud.githubusercontent.com/assets/7058465/23822030/02bca2d4-065d-11e7-9902-9c4759b0be07.png)
![stock-vector--percent-blue-circle-charts-568304968](https://cloud.githubusercontent.com/assets/7058465/23822029/02b7d1aa-065d-11e7-9fc8-275164f3366e.jpg)

**Comment by luispadron** [comment]
Have you taken a look at the [docs](http://htmlpreview.github.io/?https://github.com/luispadron/UICircularProgressRing/blob/master/docs/index.html)

This behavior can be changed by setting the `startAngle` and `endAngle`

**Comment by RajChanchal** [comment]
But docs don't mention any of such thing, bro. That's why asked.

**Comment by luispadron** [comment]
They do, it's under view styles [here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularProgressRingView.html)

Does this fix your issue?

Thanks for the question!

**Comment by RajChanchal** [comment]
I used another lib, because I couldn't find it at first look, though, your lib is good too. Thanks.
