### ISSUE TITLE
How to use gradientColor in 6.1.0

### ISSUE THREAD

**Issue by changanli** [luispadron/UICircularProgressRing#223]
:warning: **This issue will be closed if the required information is not filled** :warning:

## Version

- Version = 6.1.0

## Details

I don't know How to create gradientColor ring。Can you show Some Code?

**Comment by luispadron** [comment]
Hi there,

You set the gradient color like any other property please look at `gradientOptions` of the ring `UICircularRingGradientOptions`. Please look at the documentation for doc related questions.
