### ISSUE TITLE
Use of unresolved identifier UICircularProgressRing

### ISSUE THREAD

**Issue by Kushal-TwentyBN** [luispadron/UICircularProgressRing#225]
## Version

- Version = 6.5.0

## Details

- Has the question been answered [here](https://github.com/luispadron/UICircularProgressRing/issues?utf8=✓&q=label%3Aquestion) before?
  - No
- Please provide as much detail as possible below
  - Hi, thanks for this awesome library. Not sure if this is has been addressed before but I could not find anything related.

When I try to connect the `UICircularProgressRing` as an IBOutlet to my View Controller, I get the following error. `Property cannot be marked @IBOutlet because its type cannot be represented in Objective-C`

When I try to initialize an instance of `UICircularProgressRing` in code, I get `Use of unresolved identifier UICircularProgressRing`. I am using ObjC in some areas of the project, does this mean I need to revert back to a previous version to use this pod?

Thanks, any help is appreciated.

**Comment by luispadron** [comment]
Hey! Yes objective c support was dropped in v5. You will need to use v4 or below, sorry!

**Comment by luispadron** [comment]
Alternatively, you can use v5+ from within Swift.
