### ISSUE TITLE
Knob : How use it?

### ISSUE THREAD

**Issue by MickaelCruzDB** [luispadron/UICircularProgressRing#227]
Hi, thanks for your work with this amazing framework!

I need to add a knob/cursor to my ring in order to manage a value. However I really do not understand how to attach an action to the knob...

Any help ;-) ? Thanks!

**Comment by luispadron** [comment]
Please follow issue guidelines when posting. Have you read the [documentation](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularProgressRing.html)? 

More details on what you are trying to do will help as well, thanks.

**Comment by MickaelCruzDB** [comment]
Sorry I didn’t followed the guideline.. but could you help because even if I read the doc I do not see where to attached an event to the knob. I successfully created one, is visible on the ring but fixed..

**Comment by luispadron** [comment]
That’s not currently possible with the library, you should be able to do it with a custom gesture recognizer.

**Comment by MickaelCruzDB** [comment]
Ah ok ok. So you created the knob only for visual value's feedback ?

**Comment by luispadron** [comment]
Yes that’s correct, currently in the process of rewriting this lib so maybe i can look into adding something like that.
