### ISSUE TITLE
Start circle from top

### ISSUE THREAD

**Issue by taimur** [luispadron/UICircularProgressRing#229]
Can we set a starting point of the progress line from the top? By default, it starts from right. I cudn't find any attribute tp set the starting position of the inner line.

**Comment by luispadron** [comment]
Please take a loot at the [docs here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularRing.html#/c:@M@UICircularProgressRing@objc(cs)UICircularRing(py)startAngle)
