### ISSUE TITLE
UICircularProgressRing inside backround color?

### ISSUE THREAD

**Issue by colondeethpark** [luispadron/UICircularProgressRing#230]
:warning: **This issue will be closed if the required information is not filled** :warning:

_If it's a question about something that is happening within your code base, either post a small amount of code, or post an example project where I can try to assist.
Make sure to communic
![스크린샷 2020-03-19 12 52 57](https://user-images.githubusercontent.com/49852322/77030038-c3652d00-69e0-11ea-8428-398119d6977d.png)
ate back and keep issue updated or it will be closed_
UICircularProgressRing inside backround color?
## Version

- Version = ANSWER HERE

## Details

- Has the question been answered [here](https://github.com/luispadron/UICircularProgressRing/issues?utf8=✓&q=label%3Aquestion) before?
  - ANSWER HERE
- Please provide as much detail as possible below
  - ANSWER HERE

**Comment by luispadron** [comment]
Please follow issue guidelines, I cant help off of a single image and no description of the problem...
