### ISSUE TITLE
Add shadow to the ring

### ISSUE THREAD

**Issue by pepejeria** [luispadron/UICircularProgressRing#232]
**Is your feature request related to a problem? Please describe.**
A shadow would be necessary for when displaying a circle with a value more than 100%. Like the activity rings on the Apple Watch.

**Describe the solution you'd like**
Show a shadow all the time to get the same effect as the activity rings in the Activity app for the iPhone (which you have when u have an Apple Watch connected)

**Comment by luispadron** [comment]
Hey thanks for the request!

This isnt currently possible but I am working on rewriting this library so ill make sure to take this into consideration
