### ISSUE TITLE
Crash in some devices iOS Version 12.4.6

### ISSUE THREAD

**Issue by R-Ashh** [luispadron/UICircularProgressRing#233]
Hi, I got crash on my device with this reason, can you please tell me how to fix it?

>  reason: '[<UICircularProgressRing.UICircularProgressRing 0x104462450> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key backgroundRingColor.'

**Comment by luispadron** [comment]
This means you are using a storyboard where the key `backgroundRingColor` is set but you probably updated the library and that property no longer exists. Update your storyboard to fix.
