### ISSUE TITLE
Example code is missing.

### ISSUE THREAD

**Issue by wilwet** [luispadron/UICircularProgressRing#234]
## Bug Report

The example is missing: https://github.com/luispadron/UICircularProgressRing/tree/master/Example

#### Version

ANSWER HERE

#### Overview of what you tried to do

ANSWER HERE

#### What is the expected outcome?

ANSWER HERE

#### What is the actual outcome?

ANSWER HERE

#### Post sample code or example here

*If sample code can't be provided because it's too long, please provide a small example project,
where I can test, if you cannot provide either. There is not much I can do.*

```swift
ANSWER HERE
```
#### Have you tried fixing this yourself?

This project is open source, and I'm a student with very minimal amount of time.
Please give an attempt at fixing the issue first before creating a bug report.
This saves everyone time and benefits anyone who uses the library.
Pull requests are welcome!

**Comment by luispadron** [comment]
Yeah the example was removed as it was too annoying to maintain, sorry!

**Comment by wilwet** [comment]
no problem, it was a bit more work to get things working but ik really like it. Thnx
