### ISSUE TITLE
Progress not changing when called from a delegate callback.

### ISSUE THREAD

**Issue by MANassar** [luispadron/UICircularProgressRing#236]
## Bug Report

:warning: **Your issue will be closed if these are not filled out**. :warning:

#### Version

6.1.0

#### Overview of what you tried to do

Tried to update the progress from within a callback from a `URLSessionDelegate`

#### What is the expected outcome?

Progress should have been updated

#### What is the actual outcome?

Nothing happens. Although the completion block reports the correct value.

#### Post sample code or example here

*If sample code can't be provided because it's too long, please provide a small example project,
where I can test, if you cannot provide either. There is not much I can do.*

```swift
func uploadProgressUpdate(uploadTask: URLSessionTask, percentUploaded: Float)
    {
        DispatchQueue.main.async {
            self.progressRing.startProgress(to: CGFloat(percentUploaded), duration: 2) {
                print("Done animating! Value = \(self.progressRing.value)")
            }
        }
    }
```
#### Have you tried fixing this yourself?

I tried to debug the startAnimation method, but it seems to be running fine. I didnt invest much time into it tbh as I'm short on time myself.

**Comment by luispadron** [comment]
hm that is odd, since you're updating on the main thread it should work. I'll take a closer look
