### ISSUE TITLE
How can I set inner Ring with dash style

### ISSUE THREAD

**Issue by lieudd** [luispadron/UICircularProgressRing#237]
## Version

- Version = 6.5.0

## Details
When I set style = dashed( ex:  circularProgressRing.style = .dashed(pattern: [1.8, 8.0])), I want to ask how to set innerRing to be same dash style with outerRing. I found inner ring is progress ring, but it's style always is solid( I want it is dash also). I mean, i only need outerRing with color change in apart in which is progressed

**Comment by luispadron** [comment]
Inner ring doesnt support this mode

**Comment by lieudd** [comment]
> Inner ring doesnt support this mode

@luispadron please support for that case
