### ISSUE TITLE
Gradient color

### ISSUE THREAD

**Issue by b7anka** [luispadron/UICircularProgressRing#238]
Hello guys I hope all is well with you. Is it possible to define a gradient as de inner ring color? Thanks in advance

**Comment by sunchengbo** [comment]
I hope so

**Comment by luispadron** [comment]
From the documentation:

>`gradientOptions`
The options for a gradient ring.
If this is non-nil then a gradient style will be applied.

Please read [the docs](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularRing.html#/s:22UICircularProgressRing0aC0C15gradientOptionsAA0ac8GradientE0VSgvp)

**Comment by sunchengbo** [comment]
My question is whether the background ring can be gradient, and how to set it



发自我的iPhone


------------------ Original ------------------

**Comment by sunchengbo** [comment]
I can't use it very well

发自我的iPhone


------------------ Original ------------------

**Comment by luispadron** [comment]
Background ring can’t be a gradient.

**Comment by sunchengbo** [comment]
Thank you. I just wrote two rings

发自我的iPhone


------------------ Original ------------------

**Comment by b7anka** [comment]
Works flawlessly thanks
