### ISSUE TITLE
Timer and Progress in the same screen

### ISSUE THREAD

**Issue by JoaquinMG** [luispadron/UICircularProgressRing#244]
Hi. First, thank you for this awesome library.
I have a problem with using both timer and progress in the same screen (in fact, there are 2 progress and 1 timer). The timer works perfectly, but the progress doesn't even start.

**Comment by luispadron** [comment]
Can you describe the issue further, I can’t help without further info.

**Comment by JoaquinMG** [comment]
I'm sorry. I had a problem with several circular progress in the same screeen, but now it works (I think I had to clean and rebuild the project).
Thanks anyway.
