### ISSUE TITLE
Want to add dash style for inner ring 

### ISSUE THREAD

**Issue by lieudd** [luispadron/UICircularProgressRing#246]
I found I can not change progress ring style to dash style( progress ring is inner ring). If I set style = dash, i expect outer and inner ring are the same style, and progress change will change color of inner ring( it look a part of outer ring change color). I want it look that way( attachment). Expect you can help me find solution.
![01 Radial Progress Bars](https://user-images.githubusercontent.com/5331153/84845350-a2ab8280-b076-11ea-94af-09fe84e7c9e6.png)

**Comment by luispadron** [comment]
I'm not sure I understand your question.
Sorry for the late reply!

**Comment by lieudd** [comment]
Hi @luispadron ,
It is simple question,so, how can I make a progress-ring like image above? 
In my code, I am setup such as: 
_`circularProgressRing.style = .dashed(pattern: [1.8, 8.0])
        circularProgressRing.shouldShowValueText = false
        circularProgressRing.startAngle = 270
        circularProgressRing.shouldDrawMinValueKnob = false
        circularProgressRing.innerRingColor = UIColor.green
        circularProgressRing.outerRingWidth = 15*ratioWidthByDevice
        circularProgressRing.innerRingWidth = circularProgressRing.outerRingWidth
        circularProgressRing.outerRingColor = Constants.circularOuterRingColor`_
But, the progress-ring is solid style( I expect a dash-style)

**Comment by luispadron** [comment]
I see what you mean, the inner ring doesnt become dashed. 
This has been the behavior since the inception of this lib. Since I am not longer actively working on the UIKit version of this lib I will take this feature into consideration for the newest version. In the meantime you can totally do this yourself if you make the inner ring take the dashed style as well. Recommend modifying `UICircularRingLayer`.

**Comment by lieudd** [comment]
> I see what you mean, the inner ring doesnt become dashed.
> This has been the behavior since the inception of this lib. Since I am not longer actively working on the UIKit version of this lib I will take this feature into consideration for the newest version. In the meantime you can totally do this yourself if you make the inner ring take the dashed style as well. Recommend modifying `UICircularRingLayer`.

Thank you for the consideration
