### ISSUE TITLE
support of dark mode change inside app

### ISSUE THREAD

**Issue by ShaiAlkoby** [luispadron/UICircularProgressRing#248]
I'm changing the window overrideUserInterfaceStyle inside my app (to let the user opt out of dark mode if wanted), and every view is changing correctly except from my UICircularProgressRing views.

I've tried to change some code and change the overrideUserInterfaceStyle property of the UICircularProgressRing views but it still doesn't work.

any chance you know how to solve this?

**Comment by luispadron** [comment]
There is no built in support for this in the library.
