### ISSUE TITLE
Adding the library via SPM fails

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [luispadron/UICircularProgressRing#251]
#### Version

7.0.0

#### Xcode Version

11.6

#### iOS Version

iOS 13.0

#### Overview of what you tried to do

I tried to add the library via Swift Package Manager in Xcode (File -> Swift Packages -> Add Package Dependancy).

![Screenshot 2020-08-27 at 09 58 48](https://user-images.githubusercontent.com/2551877/91384378-08bd3e80-e84c-11ea-9ec3-715f3511c692.png)

#### What is the expected outcome?

Successful integration of the library to the Xcode project.

#### What is the actual outcome?

Adding the library fails midway with the following error.

![Screenshot 2020-08-26 at 13 27 29](https://user-images.githubusercontent.com/2551877/91277317-48c6e780-e7a0-11ea-933b-70c7ca0928e4.png)

**Comment by mwcs01** [comment]
It was working for me using branch and master until Xcode 12 GM.

**Comment by dbadmin** [comment]
I am having the same issues as @mwcs01.

**Comment by luispadron** [comment]
My bad will update to use a non fork

**Comment by serkrapiv** [comment]
Issue is still present unless you choose master branch while adding the package
