### ISSUE TITLE
Update the podspec file to include swiftUI updates 

### ISSUE THREAD

**Issue by matthew-open** [luispadron/UICircularProgressRing#252]
**Is your feature request related to a problem? Please describe.**
The podspec only includes legacy progress ring and has no swiftUI support 

**Describe the solution you'd like**
I'd like for the podspec to be updated to include the updates advertised in the readme

**Comment by luispadron** [comment]
One of the main things that changed in version 7.0 is that I will no longer be supporting anything besides SPM. This is a decision that was made because I simply do not have the time to go through the process of updating multiple dependency vendor files. I apologize for this.
