### ISSUE TITLE
Cannot add legacy version via CocoaPods

### ISSUE THREAD

**Issue by serkrapiv** [luispadron/UICircularProgressRing#257]
**Version:** 7.0.0

**Xcode version:** 12.1

**iOS version:** 13.7, 14

**Overview of what you tried to do**

I tried to instal legacy version of your library via CocoaPods. Library is installed successfully, i add 'import UICircularProgressRing' to a file where i want to use it. But then I can't access any classes in the pod. If I use, for example

`let view = UICircularProgressRing()`

I get this error: Cannot call value of non-function type 'module<UICircularProgressRing>'.

Did I forget how to add pods, or is there a bug?

**Comment by luispadron** [comment]
Version 7.0.0 is not the legacy version of the project. As it only support swift package manager, I recommend you downgrade the version.
