### ISSUE TITLE
In UICircularTimerRing give the option to be countdown rather than countup

### ISSUE THREAD

**Issue by nyeu** [luispadron/UICircularProgressRing#258]
**Is your feature request related to a problem? Please describe.**
I am using `UICircularTimerRing` but right now the only possible option in the value text is to go from 0 seconds to n seconds. 

**Describe the solution you'd like**
I would like to go from n seconds to 0 seconds. This only needs to apply to the text. I

**Describe alternatives you've considered**
I have tried to change `isClockwise` to see if that changed the timer values but it didn't.

Another alternative would be the ability to get the value at any time from the `UICircularTimerRing`. I could implement the text myself and add it to another label.

**Comment by luispadron** [comment]
Hey there, ive put this project on pause since I no longer have the time. Take a look at the open pull requests which add some of what you're looking for: https://github.com/luispadron/UICircularProgressRing/pulls
