### ISSUE TITLE
Help: Customising the ValueKnob? 

### ISSUE THREAD

**Issue by majeedyaseen** [luispadron/UICircularProgressRing#259]
Hi,

Is there a way to customize the ValueKnob? I want to customize the **valueKnob**  like below. 

![Screenshot 2020-11-23 at 3 33 31 PM](https://user-images.githubusercontent.com/30460873/99949560-3fe6b180-2da1-11eb-91d1-23f1228f4133.png)

Thanks

**Comment by luispadron** [comment]
This isnt supported and the library is no longer being maintained / updated.
