### ISSUE TITLE
Cannot find type 'UICircularProgressRing' in scope (installed via SPM)

### ISSUE THREAD

**Issue by pateldhruvil96** [luispadron/UICircularProgressRing#264]
## Bug Report
While installing UICircularProgressRing latest version in my project(written in Swift) via SPM(Swift Package Manager) it's showing this issue.
<img width="1049" alt="Screenshot 2021-05-02 at 10 16 20 AM" src="https://user-images.githubusercontent.com/45562129/116802369-c7460700-ab2f-11eb-808e-5589559c9b04.png">

**Comment by arusa** [comment]
I've got the same error after running `pod install` in an old project that still uses the legacy version and didn't get updates for quite a while.

**Comment by arusa** [comment]
![image](https://user-images.githubusercontent.com/623008/117180940-01840280-add5-11eb-8a82-44407806375c.png)

**Comment by arusa** [comment]
In my case I rolled back the update to my latest git commit and now it works again.
There must be some incompatibilities with the latest updates.

**Comment by luispadron** [comment]
Hey you should be using CocoaPods for the legacy UIKit version of the library (which is no longer being updated/maintend). 

Instructions here: https://github.com/luispadron/UICircularProgressRing/blob/master/LegacyREADME.md

You may need to set the version of the library to the legacy version
