### ISSUE TITLE
Swift Compiler Warning - Deprecated protocol inheritance

### ISSUE THREAD

**Issue by osmar106** [luispadron/UICircularProgressRing#265]
Starting with Xcode 12.5 I am getting this warning from the compiler

_Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead_

**Comment by luispadron** [comment]
This library is no longer being maintained unless there are critical issues as I no longer have the time to do so. If you'd like to open a PR doing this id happily review / merge.

If you can target iOS 14 i recommend using the Apple provided `ProgressView`
