### ISSUE TITLE
Unit text

### ISSUE THREAD

**Issue by andyjslee** [luispadron/UICircularProgressRing#27]
I'd like to be able to put a unit for the text inside the circular progress view like "GB" as you have it on the main page. How can I achieve this?

**Comment by luispadron** [comment]
Please read documentation before creating an issue, as I have stated several times...

[Docs](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularProgressRingView.html)

If you read this you will see `valueIndicator` is a string you can set to do what you want.
