### ISSUE TITLE
'Track' Colour

### ISSUE THREAD

**Issue by eggnima** [luispadron/UICircularProgressRing#28]
In your example image, how did you achieve the 'bordered' effect in the '83%' example?

I'm setting the outer and inner ring colours, but I'm unable to set the 'track' colour to be of a different colour.

Thanks!

**Comment by eggnima** [comment]
My bad! I did not notice that the 'borders' were actually part of the outer ring itself.

Do you have any advice on how I would go about setting an inner and outer border for the outer ring?

Thanks!

**Comment by luispadron** [comment]
Take a look at `viewStyle` in the [docs](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularProgressRingView.html)

For what you want do

```swift
ring.viewStyle = 2
```

Then set the widths of each ring accordingly as well as their colors.

**Comment by eggnima** [comment]
Would it be possible to have a separate border for the outer ring as per the attached image? Style 2 caters for something similar, but the outer ring does not have a separate colour for the border.

![image](https://cloud.githubusercontent.com/assets/1021142/24179340/873dab90-0ee9-11e7-8b06-601b2a28a591.png)

**Comment by luispadron** [comment]
This is not currently possible but can be added in the future. 
I currently do not have the time to add this, but the code is open source and if you would like to mess around with it and send me a pull request when you implement that would be great!

I can point you in the correct direction and help you through with questions.
