### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by AyusSalleh** [luispadron/UICircularProgressRing#3]
Can i make the progress view like this? and the label is stick beside the value knob?
<img width="265" alt="screen shot 2016-10-11 at 12 13 05 pm" src="https://cloud.githubusercontent.com/assets/20343677/19552159/488d60b4-96e1-11e6-8d47-4f0ddf3f596b.png">
<img width="259" alt="screen shot 2016-10-11 at 12 17 24 pm" src="https://cloud.githubusercontent.com/assets/20343677/19552160/48deb2b6-96e1-11e6-9d03-e4fc53eac93c.png">

**Comment by luispadron** [comment]
Yeah this looks nice, maybe in a future release when I have more time I can try to get something like this.

However feel free to grab the source code and look inside `UICircularProgressRingLayer.swift`, there you should be able to draw a circle in front of the normal progress oval.

Let me know how it goes, watch the project for any updates.

Thanks for feedback.
