### ISSUE TITLE
Wrong Progress bar value shown

### ISSUE THREAD

**Issue by Piyush08** [luispadron/UICircularProgressRing#31]
- I used start angel as -90 & my value range is 0-100.

When i try to set progress value as 50 then Circle is not half but more than half as shown below.

![screen shot 2017-03-24 at 3 15 24 pm](https://cloud.githubusercontent.com/assets/7929845/24288802/c5910704-10a4-11e7-836c-74ac994c7ec6.png)

but if I set start angel as default then it works fine.

**Comment by luispadron** [comment]
I have verified that this is indeed a bug, I'll see what I can do to fix this.

**Comment by luispadron** [comment]
Update: This has to do with the way I'm calculating the angles and not taking negatives into account, this will take a bit to figure out as I am busy all week. However in the meantime a simple work around to get the behavior you want is to go ahead and use

```swift
ring.startAngle = 270
ring.endAngle = 630
```

This will give you a full circle which starts from the top.

**Comment by bobgilmore** [comment]
I've found that if I set the `startAngle = -90.0f` , and I want to get a "full wraparound, from the top, back to top, for 100%" effect, that setting `endAngle = 270.0f` accomplishes that.  In fact, that's what I'd *expect*.

**Comment by luispadron** [comment]
@bobgilmore haha, commented at the exact same time, weird!

**Comment by luispadron** [comment]
This is "fixed" in [Version 1.4.2](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.4.2).

While it was working just fine previously it was sort of confusing for users who just wanted a full circle and custom start angle. I decided to make it easier for them, read the [changelog](https://github.com/luispadron/UICircularProgressRing/blob/master/CHANGELOG.md) and the [docs here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularProgressRingView.html)

**Comment by Piyush08** [comment]
hello
Is this new version available on cocoapods?

**Comment by luispadron** [comment]
Yes. 
Do a `pod update`
