### ISSUE TITLE
endAngle is ignored after updated to 1.4.2

### ISSUE THREAD

**Issue by graphee-gabriel** [luispadron/UICircularProgressRing#34]
#### Please provide the current version of the library you are using

- Version = 1.4.2 

#### Have you read the documentation?

- [x] Yes 
- [ ] No
 
#### Bug
I was using the library with startAngle = 45 and endAngle = 270 to have a progress view in the non-complete fraction of a circle.
After updating to 1.4.2, my circles are now complete instead of a 62.5% fraction of a circle.
The startAngle seems to still be functioning, but whatever the value of my endAngle, The circle remains complete.

**Comment by luispadron** [comment]
This is due to a new property, `fullCircle`

Please read the [change log](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.4.2)
