### ISSUE TITLE
v1.6.1 builds failed through Carthage because of Swift Language Version set to Swift 4

### ISSUE THREAD

**Issue by Tynox** [luispadron/UICircularProgressRing#41]
- Version = v1.6.1
- XCode 8.3.3

v1.6.1 builds failed through Carthage because of Swift Language Version set to Swift 4 which is not supported by XCode 8.3.3.

XCode 8.3.3 does not support Swift 4 obviously.
It'd better create a beta branch for XCode 9 testing and Swift 4 testing. And then it would not affect the final release. :)

**Comment by luispadron** [comment]
Yeah absolutely a mistake on my part and I’ll make sure to keep things branched next time. 

However, for right now you can use 1.7.x as nothing core has really changed besides project settings and language updates from 1.8.0
