### ISSUE TITLE
.setProgress() animationDuration not accurate

### ISSUE THREAD

**Issue by Black-Horse** [luispadron/UICircularProgressRing#43]
Hi!

Great work!
I am working with version 1.6.2 and I read the documentation.

I am using setProgress with an animationDuration.
When I set it to 30 seconds, the actual timespan it needs to finish is too small. It finishes about 5 seconds too early. I timed it on a real device (iPhone 5S) and on the emulator. Same result.

Thank you!

**Comment by luispadron** [comment]
Hey there what animation style are using? By default the style is a non linear style which starts of slow, builds up speed then slows down at the end. 

You could try setting `animationStyle` on the ring to something linear. Look up `CAMediaTimingFunction` or `animationStyle` in the docs to find out more. 

Let me know if this solves your issue.

**Comment by Black-Horse** [comment]
Thank you very much for your input and sorry for the stupid question!
I'll play around with the animation styles.
