### ISSUE TITLE
Need to show fractional value on progress label (question or feature)

### ISSUE THREAD

**Issue by neetin** [luispadron/UICircularProgressRing#45]
I need fractional value in progress label. It is showing only whole number. How to show value like this:
0.1% 0.2% ... 99.9% of a progress value in a label.

I need this because I am showing circular progress ring for large file download. In poor networks, it takes more time to progress from 1% to 2%. If I can show fractions, it looks effective.

Thanks!

**Comment by luispadron** [comment]
Please read the [docs](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularProgressRingView.html) before posting an issue. 

You can set `showFloatingPoint` to true, to show decimal points.

**Comment by neetin** [comment]
Thanks @luispadron
