### ISSUE TITLE
Support Setting Minimum Value

### ISSUE THREAD

**Issue by Piyush08** [luispadron/UICircularProgressRing#46]
How to set minimum value to show custom range value?

I want to show range between 250 - 500, 
How can I show that?

Thank you,

**Comment by luispadron** [comment]
A minimum value is not something that is supported. As every ring must start at 0, the max value can be changed by updating `ring.maxValue`.

**Comment by luispadron** [comment]
This has been implemented in [version 1.7.0](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.7.0).

Make sure to read the updated docs to learn about the new behavior.

Thanks!
