### ISSUE TITLE
How To Specify Version In CocoaPods?

### ISSUE THREAD

**Issue by charlieporth1** [luispadron/UICircularProgressRing#48]
How would I pull a different version (Version 1.5.5) from cocoapods I want to know because 8.3.3 xcode doesn't support swift 4 and thats the version where swift 3 is still supported

**Comment by luispadron** [comment]
UICircularProgressRing should work with both Swift 3 and Swift 4. I have tested version [version 1.7.0](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.7.0) with Xcode 8 and everything is working correctly. Could you post your podfile?

From [cocoapods](https://guides.cocoapods.org/using/the-podfile.html):

`> 0.1` Any version higher than 0.1
`>= 0.1` Version 0.1 and any higher version
`< 0.1` Any version lower than 0.1
`<= 0.1` Version 0.1 and any lower version

**Comment by charlieporth1** [comment]
Looking a "quietwars" error code its the exact same one I had. 

https://forums.developer.apple.com/thread/62335
Also this is the coming out from the debug console 

dyld: Library not loaded: @rpath/GTMSessionFetcher.framework/GTMSessionFetcher

  Referenced from: /var/containers/Bundle/Application/1F189DD9-56DE-4E76-9DCB-4EB02C9BEE19/Studioso.app/Studioso

  Reason: no suitable image found.  Did find:

/private/var/containers/Bundle/Application/1F189DD9-56DE-4E76-9DCB-4EB02C9BEE19/Studioso.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher: code signing blocked mmap() of '/private/var/containers/Bundle/Application/1F189DD9-56DE-4E76-9DCB-4EB02C9BEE19/Studioso.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher'

/private/var/containers/Bundle/Application/1F189DD9-56DE-4E76-9DCB-4EB02C9BEE19/Studioso.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher: code signing blocked mmap() of '/private/var/containers/Bundle/Application/1F189DD9-56DE-4E76-9DCB-4EB02C9BEE19/Studioso.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher'

/private/var/containers/Bundle/Application/1F189DD9-56DE-4E76-9DCB-4EB02C9BEE19/Studioso.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher: code signing blocked mmap() of '/private/var/containers/Bundle/Application/1F189DD9-56DE-4E76-9DCB-4EB02C9BEE19/Studioso.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher'

/private/var/containers/Bundle/Application/1F189DD9-56DE-4E76-9DCB-4EB02C9BEE19/Studioso.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher: code signing blocked mmap() of '/private/var/containers/Bundle/Application/1F189DD9-56DE-4E76-9DCB-4EB02C9BEE19/Studioso.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher'

/private/var/containers/Bundle/Application/1F189DD9-56DE-4E76-9DCB-4EB02C9BEE19/Studioso.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher: code signing blocked mmap() of '/private/var/containers/Bundle/Application/1F189DD9-56DE-4E76-9DCB-4EB02C9BEE19/Studioso.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher'

(lldb) 

Thanks

**Comment by charlieporth1** [comment]
I got that problem fixed, but would you mind helping me with another problem I have - as you seem like a knowledgeable dev.

**Comment by luispadron** [comment]
Glad you got it working, I'm closing this issue.

This isn't the appropriate place to help you with that, however, If you want you can shoot me an email at [heyluispadron@gmail.com](mailto:heyluispadron@gmail.com) with your project and I can take a look at it.
