### ISSUE TITLE
Restart progress available?

### ISSUE THREAD

**Issue by danielsGit** [luispadron/UICircularProgressRing#51]
Is it possible to restart the progress? First time, it works fine. But i want restart progress by clicking button.
I've called setProgress func again but it doesnt work.
I appreciate any help

**Comment by luispadron** [comment]
Can you please follow the issues guideline? 
It takes longer when you dont, because now I ask you things you would've answered.

1. Version number?
2. Please show example code of what you're dooing.

**Comment by danielsGit** [comment]
I installed with CocoaPods today
pod 'UICircularProgressRing'

Here is my code.
func startCountDown() {
       timeLeftProgBar.delegate = self
       timeLeftProgBar.setProgress(value: 360, animationDuration: 5) {
             // finished. Do some action          
        }
}

@IBAction func onClkReBroadcast(_ sender: Any) {
        // want restart progress
         self.startCountDown()
 }

**Comment by luispadron** [comment]
Cool, to reset the progress ring to the value you want. 

For example if you want to go back to zero 

```swift
/// This will set the rings value to 0 with no animation. 
progressRing.setProgress(0, duration: 0)
```

Let me know if this works for you, or close the issue.

**Comment by danielsGit** [comment]
Great~ it works. Closed issue
