### ISSUE TITLE
Start value

### ISSUE THREAD

**Issue by NVAT** [luispadron/UICircularProgressRing#52]
How can set start value in progress bar

**Comment by luispadron** [comment]
Please read the docs before posting a question.

**Comment by NVAT** [comment]
I have red,but could not find,I wanna like this photo
![simulator screen shot sep 16 2017 18 48 14](https://user-images.githubusercontent.com/16933227/30513171-a27e6d56-9b0f-11e7-9d22-a5e139a29c37.png)

**Comment by luispadron** [comment]
It’s in the docs. 
Changing the value of progressRing.value is what you want to do.

**Comment by NVAT** [comment]
Did you mean `@IBInspectable open var value: CGFloat` ?
