### ISSUE TITLE
Applications Using UICircularProgressRing

### ISSUE THREAD

**Issue by luispadron** [luispadron/UICircularProgressRing#54]
## Do you use this library?

Hey everyone, thanks for using this library and helping me build it!

If you're using the library in a readily available application and would like to show it off,
post a comment with a link to your application!

I'll feature a compilation on the homepage of the library once a list is curated.

**Comment by aershov24** [comment]
Hi Luis! Thanks again for the awesome library. 

Just released a new version of my Sun Safety app with UICircularProgressRing as a main UI component:
https://itunes.apple.com/us/app/uvi-mate-global-uv-index-now/id1207745216?mt=8 

Cheers.
Alex Ershov.

**Comment by luispadron** [comment]
Awesome I’ll add it to the homepage of the app soon.

**Comment by NikolaiSa** [comment]
Hi Luis, great job with this UI control! Here's how we're using it for HotelTonight:

![perksuplevel](https://user-images.githubusercontent.com/746234/35939469-119c0326-0c01-11e8-85df-19206f18e8cc.gif)

https://itunes.apple.com/app/id407690035?mt=8

Is there a way to animate the inner and outer ring width? I tried to change the values in an animation block without success. 

Thanks!

**Comment by luispadron** [comment]
Oh wow, that's awesome to see it being used in such a popular application, thanks for letting me know, I'll add it to README.

As for animating the widths, that's not currently possible, but feel free to open a feature request and I'll try and get it done when I can, thanks again!

**Comment by eladhayun** [comment]
Hi, Thanks for this awesome library, I used it in my Fast Lane app which shows the current price of the busiest road in Israel in real time.

[https://itunes.apple.com/us/app/הנתיב-המהיר/id1320456872?mt=8](url)

![img_1260 trim](https://user-images.githubusercontent.com/5832456/39741762-c3b4cece-52a3-11e8-9ff9-12d3a9d5cc9d.gif)

**Comment by nickdnk** [comment]
We use it on our newly redesigned customer app. It simply counts to 60 (lower left corner) and then refreshes the view. It lets users know they're looking at a recently updated version of the tables. https://media.giphy.com/media/5n1VqqpQMCCKMT4flP/giphy.gif

**Comment by luispadron** [comment]
@nickdnk, awesome! Love to see the library being used in production apps.

**Comment by AndrewBarba** [comment]
Been using it in Barstool for over a year now, great work.

https://itunes.apple.com/us/app/barstool-sports/id456805313

![simulator screen shot - iphone xs - 2019-02-08 at 13 07 45](https://user-images.githubusercontent.com/1316152/52496862-93731580-2ba2-11e9-8627-7505558d3c5c.png)

(Also upgrading to 5.0 was a 1 line change for me)

**Comment by luispadron** [comment]
@AndrewBarba, awesome to hear! thanks for sharing, added it to the readme.

**Comment by Stijnk008** [comment]
> ## Do you use this library?
> Hey everyone, thanks for using this library and helping me build it!
> 
> If you're using the library in a readily available application and would like to show it off,
> post a comment with a link to your application!
> 
> I'll feature a compilation on the homepage of the library once a list is curated.

Awesome repo I use it in my project: http://88-days.com

**Comment by luispadron** [comment]
@Stijnk008, very nice! I'll add it to README.

**Comment by bookbotdev** [comment]
Hi @luispadron, thanks for your great library.
We used `UICircularProgressRing` to show the children's reading progress on our Bookbot application https://itunes.apple.com/us/app/bookbot-reading-books-for-kids/id1325919626?mt=8
This is a book reading app for practicing children, which can help children to improve their speaking & reading skills

![Simulator Screen Shot - iPad Air 2 - 2019-04-15 at 14 47 15](https://user-images.githubusercontent.com/49635791/56115838-91f10f80-5f8e-11e9-99b8-d800dbc31dab.png)

**Comment by luispadron** [comment]
@bookbotdev aw that's cool! thanks for sharing.

**Comment by zulkis** [comment]
Luis Padron

Hi @luispadron, great job on this library!
We used `UICircularProgressRing` in [car2go](https://apps.apple.com/us/app/car2go/id514921710) to show for how long car2go is still reserved.
car2go is free-floating carsharing which provides access to the great cars around the world with just click of a button :)

Thank you @luispadron!

**Comment by theofficejackpot** [comment]
Hi Luis, we use your ring in our Dividend Tracking application.  Thank you so much for your work.
![Screenshot 2019-12-16 at 10 33 13 AM](https://user-images.githubusercontent.com/45904198/70919832-91ae8580-1fef-11ea-86c1-984be0366328.png)

**Comment by dhavalSA** [comment]
> Hi Luis! Thanks again for the awesome library.
> 
> Just released a new version of my Sun Safety app with UICircularProgressRing as a main UI component:
> https://itunes.apple.com/us/app/uvi-mate-global-uv-index-now/id1207745216?mt=8
> 
> Cheers.
> Alex Ershov.

will you please share your updated copy of this library , i have same look in my project , so it will save my time

**Comment by thefabbulus** [comment]
Hello @luispadron , and thanks for the amazing work!

[Noon Happen](https://apps.apple.com/app/id1477310602) also uses `ÙICircularProgressRing` since version 1!

**Comment by luispadron** [comment]
Thank you all!
