### ISSUE TITLE
I am not able to getting animation by programmatically creating UICircularProgressRingView object

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [luispadron/UICircularProgressRing#60]
I am trying to display UICircularProgressRingView in tableviewcell, and I am creating by programmatically, but the animation not happening this way, can you give any suggestions to fix this? And its coming like this, dashes are not coming properly. 
![screen shot 2017-10-18 at 3 25 56 pm](https://user-images.githubusercontent.com/8393997/31712461-c4cc71a6-b418-11e7-8c54-76dcb52e2d60.png)

 If possible, can you please provide documentation to get style no 3 for programmatically achieve?

**Comment by luispadron** [comment]
Please understand how issues are supposed to work on GitHub. I am the only person maintaining this project and even though its open source, the github issues section is not just for tech support. You have posted two questions,  none of these are bugs and some have been answered before, so please research before posting an issue. You also have not followed the guideline that I require before responding to an issue as it speeds the process up. 

If you are trying to animate the ring in cellForRow then the animation will not be shown as this happens before the view appears, do the animation in cellDidAppear or viewDidAppear. As for the other question this heavily documented and all you need to do is read the documentation and experiment a bit with the different styles. Please be considerate of other people’s time when you post a question that can be answered by you doing more work/research. 

Thanks for using the library
