### ISSUE TITLE
Bug, calculation of progress if minValue != 0

### ISSUE THREAD

**Issue by NikolaiSa** [luispadron/UICircularProgressRing#61]
- Detailed overview of what you are trying to accomplish

I want to show the progress ring with a minimum value of 100 and maximum value of 200. Both startAngle and endAngle are set to 270 (12:00 o'clock position). 

- What is the expected outcome?
When I set the value to 150 I expect half of the circle to be filled.

- What is the actual outcome?
Only a quarter of the circle is filled

The following code in drawInnerRing:

`innerEndAngle = (value - minValue) / maxValue * 360.0 + startAngle`

should be 

`innerEndAngle = value / maxValue * 360.0 + startAngle`

**Comment by luispadron** [comment]
Which version are you using? I remember fixing this in another release and have had a pull request which expands upon this (#53).

**Comment by NikolaiSa** [comment]
You're right. I was using 1.7.2. You fixed it in 1.7.3. Sorry for the confusion. It's working great now.
