### ISSUE TITLE
Does not animate in TableViewCell

### ISSUE THREAD

**Issue by uknowmeright** [luispadron/UICircularProgressRing#63]
- Version = 1.7.4

When i try to put the view inside of a TableViewCell and animate the result It never animates. I have tried using the following code but it does not seem to work. Am I missing something here?

```
override func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {

        //ring animation
        if let theCell = cell as? ProgressCell{
            theCell.progressView.setProgress(value: CGFloat(theCell.unpaidValue), animationDuration: 4.0, completion: {
                theCell.layoutIfNeeded()
            })
        }
    }
```

**Comment by luispadron** [comment]
This is impossible to debug with the following code sample you have provided. 

This is reliant on how your cells are being loaded as well as so many other factors. As for how you’re using the library yes that seems right. Not sure why it’s not animating. 

I believe it may have to do with the function you’re calling for animation, as the view must be already showing for animations to show. Also not sure why you call layoutIfNeeded in the completion, this may be an issue as well. 

Without a project or some more code I can’t really help. Look through older issues as I remember seeing something similar to this.

**Comment by uknowmeright** [comment]
I was able to figure this out.
Very odd since I had to force an animation and THEN run the desired animation for it to function correctly. Not sure why this is the case but at least it works now. Here is the code for anyone dealing with this. 

 ```
UIView.animate(withDuration: 0.1, animations: {
            self.progressView.setProgress(value: 0.0, animationDuration: 0.0)
            self.layoutIfNeeded()
        },completion: { finished in
            UIView.animate(withDuration: 1.5, animations: {
                self.progressView.setProgress(value: CGFloat(self.unpaidValue), animationDuration: 1.5, completion: {
                    self.layoutIfNeeded()
                })
            })
        })
```

**Comment by luispadron** [comment]
This leads me to believe that the function in which you're calling this is not on the main thread. 
Thanks for posting your solution.

**Comment by uknowmeright** [comment]
Yes I think you are right Since the tableview Crashes if you force it on the main thread. Also Note that the percentage does not update automatically in a tableViewCell as well. My solution was to just hide the included percentage label and create my own custom one.

**Comment by luispadron** [comment]
Yeah, sadly there's no easy way I can think of for animating cells as soon as they appear. 
This is why I usually recommend animating rings on or after viewDidAppear.
