### ISSUE TITLE
How to set a color start and a color end with a gradient just one time?

### ISSUE THREAD

**Issue by AndreaMiotto** [luispadron/UICircularProgressRing#64]
Hi, I'm using your library but I noticed that if you use the gradient colors, the gradient will be applied at the 2 times between the 2 colors, one in the middle and one at the end of the circle.

What If I want it just at the middle? 

like this one?

<img width="324" alt="schermata 2017-11-15 alle 17 06 05" src="https://user-images.githubusercontent.com/11211914/32846485-aa30cdc2-ca27-11e7-9d86-6d1f46d64ac5.png">

**Comment by luispadron** [comment]
Not exactly sure what you mean there are ways to position the gradient, which are described in the [docs](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Enums/UICircularProgressRingGradientPosition.html)

**Comment by AndreaMiotto** [comment]
I would like to have a start color and a end color, they blend in the middle but not in the end...

Apparently this will automatically blend the colors either in the middle and in the end, I'm looking for a method to avoid this

**Comment by luispadron** [comment]
The way the gradient is drawn depends on where your angle starts and where your gradient starts and ends. There isn’t any easy way to make radial gradients in iOS. 

So gradients for this library are drawn in a rectangular fashion and then masked. I’d say experiment with the possible options for gradient angles.

**Comment by AndreaMiotto** [comment]
Hi Luis, I have 2 colors, white and clear, I want that the white starts from 0 until 75 of the circle and the clearer 76 to 99 of the circle. I can't understand how to set it... A little help?

**Comment by luispadron** [comment]
As I said this isn't possible as currently, you cant draw radial gradients with this library.
Also, clear isn't a color, thus it won't show up in anything you use it for.
