### ISSUE TITLE
The delegate's `didUpdateProgressValue(to newValue: CGFloat) ` is called many times even if the `animationDuration` is 0. 

### ISSUE THREAD

**Issue by slash7** [luispadron/UICircularProgressRing#65]
I'm using the last cocoapod.

I use the progress to go from 0 to 100 in 10 seconds with a linear animation:
```
circularProgress.animationStyle = kCAMediaTimingFunctionLinear
circularProgress.setProgress(value: 100, animationDuration: 10.0)
```

Once 100 is reached, I reset the progress back to 0 to reuse it later.
```
func finishedUpdatingProgress(forRing ring: UICircularProgressRingView) { 
    circularProgress.setProgress(value: 0, animationDuration: 0)
}
```

**Issue:**
When reseting to 0 using: `circularProgress.setProgress(value: 0, animationDuration: 0)` , the delegate's `didUpdateProgressValue(to newValue: CGFloat) ` is called for 10 seconds even if the `animationDuration` is 0.

**Comment by luispadron** [comment]
`didUpdate` should be called whenever you call `setProgress`. However, it should be sending you the latest value that was set. I’m going to file this as a bug and see when I have a chance to look at it since I’m really busy currently.

**Comment by slash7** [comment]
Edit: I think I'm creating an infinite loop by calling `circularProgress.setProgress(value: 0, animationDuration: 0)` in `finishedUpdatingProgress()`

**Comment by luispadron** [comment]
Yes this would definitely create a cycle.

**Comment by slash7** [comment]
Yeah, sorry, it's that. Got it working.
```
func finishedUpdatingProgress(forRing ring: UICircularProgressRingView) { 
     if ring.value != 0 {
            circularProgress.setProgress(value: 0, animationDuration: 0)
        }
}
```

**Comment by slash7** [comment]
I'll close this.
