### ISSUE TITLE
Add support for choosing animation direction

### ISSUE THREAD

**Issue by hugobisson** [luispadron/UICircularProgressRing#70]
Hi Luis,

First of all, thanks for this great lib, it saved me a lot of time !

I'm trying to use it to do a countdown, but currently, the animation rotational direction is clockwise and we can only animate from a minValue to a maxValue (increment the value).

I was wondering if it'll be possible to choose the rotational direction (clockwise or counter-clockwise) and to choose to increment or decrement the value, and so add the possibility to animate from a maxValue to a minValue. 

Thanks for your time.

PS: In my case the idea is to do this :

![capture d ecran 2018-01-10 a 15 49 22](https://user-images.githubusercontent.com/15252914/34778591-0582a7f0-f61e-11e7-8f95-91d0c1e56101.png) -> ![capture d ecran 2018-01-10 a 15 48 56](https://user-images.githubusercontent.com/15252914/34778605-1165a5f4-f61e-11e7-9c91-3183c2fd9649.png) -> ![capture d ecran 2018-01-10 a 15 48 32](https://user-images.githubusercontent.com/15252914/34778616-163481d6-f61e-11e7-91ec-e0838d35754c.png) ...

**Comment by luispadron** [comment]
> we can only animate from a minValue to a maxValue (increment the value)

This isn't true. While the `minValue` and `maxValue` are required, it doesn't mean you must go in a positive direction. The animation for the ring is extremely fluid, that is to say, you can absolutely start at 10 and go to 4. Here is an example:

```swift
progressRing.maxValue = 10
progressRing.minValue = 0
progressRing.setProgress(10, animationDuration: 0.0) // Start ring at 10
progressRing.setProgress(4, animationDuration: 2.0) // Animate ring to value 4
```

The above will start ring at 10 and animate back to 4. The animation from 10 to 4 will be in the opposite direction that it originally animated in (clockwise) thus animating to 4 will be done in a counter-clockwise direction like you said you wanted above.

As for adding a property to allow you to change animation direction, I can look into it. I believe when I was first designing the library I had this option but it was more work than I thought was worth it. However, I can look at it again, or if you would like to add the changes since this library is open source, I can guide you if you need assistance.

**Comment by hugobisson** [comment]
Thanks for your help, that's exactly what i was looking for. 
I'm sure adding a property to allow to change animation direction will be useful for someone, but, thanks to you, i don't need it anymore for now and, sadly, i don't have time to spend on it.
Thanks again !

**Comment by nonpensavo** [comment]
I am trying to achieve the same result with following code
```
popupProgressRing.maxValue = 10
popupProgressRing.minValue = 0
        
popupProgressRing.startProgress(to: 10, duration: 0)
popupProgressRing.startProgress(to: 4, duration: 5)
```
But animation just keep starting from 0.  
Even if I divide (for testing purposes only)
popupProgressRing.startProgress(to: 10, duration: 0)
and then after touch event start
popupProgressRing.startProgress(to: 4, duration: 5) 
It just start from 0% and goes to 40%. 

Using latest XCode Version 11.1 (11A1027) and Swift 5.1

**Comment by nonpensavo** [comment]
> Thanks for your help, that's exactly what i was looking for.
> I'm sure adding a property to allow to change animation direction will be useful for someone, but, thanks to you, i don't need it anymore for now and, sadly, i don't have time to spend on it.
> Thanks again !



> > we can only animate from a minValue to a maxValue (increment the value)
> 
> This isn't true. While the `minValue` and `maxValue` are required, it doesn't mean you must go in a positive direction. The animation for the ring is extremely fluid, that is to say, you can absolutely start at 10 and go to 4. Here is an example:
> 
> ```swift
> progressRing.maxValue = 10
> progressRing.minValue = 0
> progressRing.setProgress(10, animationDuration: 0.0) // Start ring at 10
> progressRing.setProgress(4, animationDuration: 2.0) // Animate ring to value 4
> ```
> 
> The above will start ring at 10 and animate back to 4. The animation from 10 to 4 will be in the opposite direction that it originally animated in (clockwise) thus animating to 4 will be done in a counter-clockwise direction like you said you wanted above.
> 
> As for adding a property to allow you to change animation direction, I can look into it. I believe when I was first designing the library I had this option but it was more work than I thought was worth it. However, I can look at it again, or if you would like to add the changes since this library is open source, I can guide you if you need assistance.

I am trying to achieve the same result with following code
```
popupProgressRing.maxValue = 10
popupProgressRing.minValue = 0
        
popupProgressRing.startProgress(to: 10, duration: 0)
popupProgressRing.startProgress(to: 4, duration: 5)
```
But animation just keep starting from 0.  
Even if I divide (for testing purposes only)
`popupProgressRing.startProgress(to: 10, duration: 0)` 
and then after ensuring that current value is 100%, trigger touch event starts animation
`popupProgressRing.startProgress(to: 4, duration: 5) `
But it just start from 0% and goes to 40%. 

Using latest XCode Version 11.1 (11A1027) and Swift 5.1
