### ISSUE TITLE
Please add animation support for several parameters

### ISSUE THREAD

**Issue by NikolaiSa** [luispadron/UICircularProgressRing#74]
Please allow for the below parameters to support animation:

innerRingWidth
innerRingColor
outerRingWidth
outerRingColor

Maybe audit all parameters for supporting animations where it makes sense.

Thank you!!

**Comment by luispadron** [comment]
I'll look into this when I get some free time, thanks for posting!

**Comment by luispadron** [comment]
Added in [version 1.8.0](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.8.0)
