### ISSUE TITLE
start the ring from top, not from 45 degree/right

### ISSUE THREAD

**Issue by iPhoNewsRO** [luispadron/UICircularProgressRing#8]
how can i implement this? start the ring from top, not from 45 degree/right
thanks

**Comment by luispadron** [comment]
You can alter the angles for the ring using the `startAngle` and `endAngle` properties.

Please take a look at the documentation, as this isn't an issue: [DOCUMENTATION](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularProgressRingView.html)
