### ISSUE TITLE
Attribute removed

### ISSUE THREAD

**Issue by marcoslacerda** [luispadron/UICircularProgressRing#82]
Hello,

You remove the attribute ringStyle????

After update my code not working:

`progress.ringStyle = .ontop`

Thanks for your help

**Comment by luispadron** [comment]
Follow issue guidelines before posting an issue

**Comment by Ruyven** [comment]
I have the same problem. Are there update guidelines or something explaining what we're supposed to use instead of ringStyle now?

**Comment by luispadron** [comment]
Can you guys please provide your configurations?
What version of the library are you using, what Xcode version, etc.

The issue guideline specifically asks for this info so that I can figure out whats going on faster.

**Comment by luispadron** [comment]
As far as I'm aware this has not been changed and the `ringStyle` property is still there:

[View it here](https://github.com/luispadron/UICircularProgressRing/blob/1a44c8c73c9042fe2b428ea44cac6a86b6ca498b/UICircularProgressRing/UICircularProgressRingView.swift#L230)

**Comment by Ruyven** [comment]
Version=v1.8.4
Read the documentation: ✓
Installed via: Carthage

Problem: The swift compiler complains that UICircularProgressRingView has no member 'ringStyle', 'fullCircle' or 'outerCapStyle'. It does, however have a member outerRingCapStyle [Int] and viewStyle [Int]. (Did Carthage somehow give me an older version?)

Incident that most likely caused the problem: After updating Xcode to version 9.3, I had to recompile all of my Carthage classes manually. Xcode started giving me the error after I ran `carthage update UICircularProgressRing --platform iOS` with the new xcode tools version.

(Thank you, I found the ISSUE_TEMPLATE now!)

**Comment by luispadron** [comment]
Seems like Carthage is giving you an older version of the library as `viewStyle` was renamed to `ringStyle`

**Comment by Ruyven** [comment]
Gotcha. I got it to work by removing it from Carthage and installing it via CocoaPods instead. Really strange, I never had this problem with Carthage before!
Carthage is version 0.25.0 if it helps.. let me know if I can give you any other configuration info to help! You did write that using CocoaPods was recommended 😅

Thank you for the prompt responses!

**Comment by luispadron** [comment]
Yah not sure what's going on with Carthage, I'll update this issue if I find out any more information.

And yeah, CocoaPods is recommended for this lib since Carthage doesn't really support Interface builder libraries.

**Comment by Ruyven** [comment]
Ah that's why!
I'll update Carthage to the newest version (0.29.0) and try again later today, maybe it's just a problem with the old Carthage and the new Xcode not playing nice together.

**Comment by Ruyven** [comment]
Still the same problem with Carthage 0.29.0. Looks like it's a problem with Xcode 9.3 (9E145).
It seems independend of macOS version, it's the same on both macOS 10.13.3 and 10.13.4.

**Comment by luispadron** [comment]
This should now be fixed. 
Try running `carthage update --platform iOS`

It should grab and build the latest version: [1.8.5](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.8.5)

**Comment by luispadron** [comment]
I'm going to close this since I tested it and it seems to be working, please reopen if any other issues come up.
