### ISSUE TITLE
Carthage build is outdated

### ISSUE THREAD

**Issue by hohteri** [luispadron/UICircularProgressRing#85]
- Version = v1.8.5
- Detailed overview of what you are trying to accomplish

Use carthage version of the library

- What is the expected outcome?

Carthage version would be up-to-date

- What is the actualy outcome?

Carthage builds a version from the Examples workspace due to designed behaviour:
https://github.com/Carthage/Carthage/issues/1754
https://github.com/Carthage/Carthage/issues/1521

If I remove the Examples directory, the correct version is built using Carthage.

**Comment by luispadron** [comment]
Reading the Carthage issues it doesn’t seem like this will be getting fixed, so this sucks since it seems the only way to build stuff now is remove the examples then add then back in after the build.

**Comment by hohteri** [comment]
I have never worked with workspaces in Xcode but shouldn’t it have a reference to the original code, not a dated copy of it? Alternatively one could do a symlink I guess?

I don’t actually know why this problem occurs only with Xcode 9.3, I didn’t have it with Xcode 9.2. And I only noticed it because the Examples contain a copy of the actual project without the @objc definitions thus failing my main project.

**Comment by luispadron** [comment]
This should now be fixed, I think the current solution is to put the source files/project in a "src" directory then run Carthage from there. I've updated the 1.8.5 release framework to be this newly built one, please reopen if there are still issues.
