### ISSUE TITLE
Customize dashed style

### ISSUE THREAD

**Issue by kiokumicu** [luispadron/UICircularProgressRing#87]
READ BEFORE POSTING AN ISSUE

_Not following these guidelines may result in me ignoring or closing your issue, please carefully read and submit an appropriate issue as it helps with time and fixes._

#### Please provide the current version of the library you are using

- Version = v1.8.5

#### Have you read the documentation?

- [ x] Yes 

Hi!
Thx for you work!
How I can customize strip thickness in dashed style ring ?

**Comment by luispadron** [comment]
The width of the dashes is handled by `outerRingWidth` like the documentation states.
