### ISSUE TITLE
Bug -- Trying to implement Anti-Clock wise animation resulting in no clear for outer ring  

### ISSUE THREAD

**Issue by SaluBhayo** [luispadron/UICircularProgressRing#88]
#### Please provide the current version of the library you are using

- Version = 2.0.0

#### Have you read the documentation?

- Yes 
 
	If no, read the docs [here](http://htmlpreview.github.io/?https://github.com/luispadron/UICircularProgressRing/blob/master/docs/index.html) before posting an issue

#### Is it a bug? Provide the following
- Detailed overview of what you are trying to accomplish

I am trying to implement anti-clock wise rotation for the remaining time for event to expire. I set start angle at 270 and end angle is -90

- What is the expected outcome?
   Anti-clock wise rotation should work and inner and outer rings should be shown
- What is the actually outcome?
    Inner Ring working perfectly but outer ring is not appearing
- Either post sample code, or example project where isssue can be recreated
-- Please find attached code
[Example.zip](https://github.com/luispadron/UICircularProgressRing/files/1924880/Example.zip)

**Comment by luispadron** [comment]
The version you provided in the example project is `1.4.1` which had issues with ring layout, please update your pod to the latest version.

**Comment by SaluBhayo** [comment]
What is the latest Version number?

**Comment by luispadron** [comment]
2.0.0 like it shows in the Releases tab

**Comment by SaluBhayo** [comment]
But when I reinstalled the pod its giving 1.7.5 version 
(https://user-images.githubusercontent.com/12893784/39140824-3232c376-473f-11e8-90fb-89d5413fe6ff.png)

**Comment by luispadron** [comment]
Are you doing `pod update`?

**Comment by SaluBhayo** [comment]
No, I commented pod in podfile and ran pod Install, then uncommented pod in podfile and ran pod install again (I didn't set any pod version manually)

**Comment by SaluBhayo** [comment]
I have added new version but found another bug

**Comment by luispadron** [comment]
And what is the bug?
