### ISSUE TITLE
Gradient progress color question

### ISSUE THREAD

**Issue by StevenVerheyen** [luispadron/UICircularProgressRing#89]
On the image, one of the progress ring has a gradient color.
I am wondering how to achieve this. Is it also possible to specify at what value which color should be set?

Tnx!

**Comment by StevenVerheyen** [comment]
Question is answered in the docs ;)

**Comment by happiehappie** [comment]
Error: Cannot load file https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularProgressRingView.html

**Comment by luispadron** [comment]
I renamed the class and didn’t update readme, thanks for the reminder. Will do so now
