### ISSUE TITLE
View fails to render on storyboard after update of latest version of UICircularProgressRing

### ISSUE THREAD

**Issue by kudzaiTnexus** [luispadron/UICircularProgressRing#90]
```
.../Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for HomeViewController (K44-BH-Vk2): dlopen(UICircularProgressRing.framework, 1): no suitable image found.  Did find:
	UICircularProgressRing.framework: required code signature missing for 'UICircularProgressRing.framework'
```

I update to the latest version of the library which is 2.0 and i started experiencing this issue. Could anyone give me a pointer asto what might be a solution to this. I even downgraded to the old 1.8.4 but with no success still getting same error. The view is just empty now instead of showing UIComponents.

<img width="567" alt="screen shot 2018-05-05 at 04 30 51" src="https://user-images.githubusercontent.com/32536638/39658898-2d41b304-501d-11e8-90ae-4a94ced38137.png">

**Comment by luispadron** [comment]
This is the same issue from #84, the only thing you can do right now is downgrade to an older version of CocoaPods, where this issue doesn't exist. It's not something I can fix as it has nothing to do with the library but the way CocoaPods handles `@IBDesignable` frameworks.

**Comment by luispadron** [comment]
I'm going to close this simply because it's nothing I can do, feel free to follow [this issue](https://github.com/CocoaPods/CocoaPods/issues/7606) for updates

**Comment by kudzaiTnexus** [comment]
Thank you for your response which version of cocoapods would you recommend

**Comment by mohammedtabish** [comment]
Downgraded to 1.4.0 , still the same issue :(

**Comment by luispadron** [comment]
Again, sorry but this isn't something I can fix. I know that the maintainers at CocoaPods are working on a fix, check [this](https://github.com/CocoaPods/CocoaPods/issues/7606) for more information.

**Comment by mohammedtabish** [comment]
Thanks for the quick replies man 🥂

**Comment by RaoulNL** [comment]
Hi Luis,
I'm using your library (version 2.1.0) with Xcode 9.4.1 in a sample project in which the deployment target has been set to iOS 11.4. After installing Cocoapods says this message:

> Automatically assigning platform `ios` with version `9.3` on target `CircularAnimation` because no platform was specified. Please specify a platform for this target in your Podfile.

As soon as I set the class of a UIView to UICircularProgressRingView I get the same error in Xcode as kudzaiTnexus described. Is this still a problem at Cocoapods? (b.t.w. I use Cocoapods version 1.5.3)

However the project complies and runs perfectly. Could you give a heads up?

**Comment by luispadron** [comment]
Please post a new issue and I’ll look at it whenever I get a chance, thanks!
