### ISSUE TITLE
outerRingColor: changing color with animation

### ISSUE THREAD

**Issue by giofid** [luispadron/UICircularProgressRing#92]
- Version = 2.1.0
- Have you read the documentation? Yes 

Hi,
`outerRingColor` is inside `animatableProperties` array, but when I try to do
```
ring1.animateProperties(duration: 3, animations: {
     ring1.outerRingColor = .yellow
})
```
the `outerRingColor` is changed, after 3 seconds, without animation.

If I try the same thing with `outerRingWidth` all works fine: the `outerRingWidth` is changed with animation.

Is there a way to change `outerRingColor` or `innerRingColor` with an animation?

**Comment by luispadron** [comment]
This seems like the same issue as #79. I don’t really know how to fix this but I’ll try and take a look at it, if you would have any idea feel free to open a PR.
