### ISSUE TITLE
How do I set secondary color?

### ISSUE THREAD

**Issue by heruvilius** [luispadron/UICircularProgressRing#93]
Hello. I find you framework very handy. However, I am unable to understand one thing:

By using `innerRingColor` property I set the primary color (i.e. the color that represents my current value). How do I change the secondary color from `.clear` to something else (i.e. the color that represents the rest of the ring).

The case is shown on the left bottom example from [UICircularProgressRing page](https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/.github/styles-banner.png).

Thank you for your work.

**Comment by luispadron** [comment]
There are two properties which dictate the ring color. `innerRingColor` and `outerRingColor` please read the docs for more info
