### ISSUE TITLE
Question? Is it possible that the ring rotates in an inter-determined way?

### ISSUE THREAD

**Issue by haroldogtf** [luispadron/UICircularProgressRing#94]
Is it possible that the ring rotates in an inter-determined way? Not just going up to certain value?

**Comment by luispadron** [comment]
Please follow issue templates before posting an issue.

Not sure what you are asking with this question, post an example image or describe with more detail

**Comment by haroldogtf** [comment]
Sorry, I will put in the template.
I don't want to use a setProgress to get up to a certain value. I would like you to use continuously.
Something linge this:

https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fb%2Fb1%2FLoading_icon.gif&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3ALoading_icon.gif&docid=bZPsBzNaE_qgNM&tbnid=L6frLyk-WNG0ZM%3A&vet=10ahUKEwiC8-HT557bAhXDh5AKHdArCjwQMwjkASgCMAI..i&w=441&h=291&safe=off&bih=710&biw=1440&q=loading%20gif&ved=0ahUKEwiC8-HT557bAhXDh5AKHdArCjwQMwjkASgCMAI&iact=mrc&uact=8

**Comment by haroldogtf** [comment]
Ok! Thank you!
