### ISSUE TITLE
Feature Request: Add ability to perform loading-like animation for indefinite amount of time

### ISSUE THREAD

**Issue by haroldogtf** [luispadron/UICircularProgressRing#95]
**Is your feature request related to a problem? Please describe.**
This feature will help to show the progress when you have to wait for something that the time is indeterminate.

**Describe the solution you'd like**
The feature request  is a based on this question
https://github.com/luispadron/UICircularProgressRing/issues/94
Could load infinite

**Additional context**
Like this:
![img](https://upload.wikimedia.org/wikipedia/commons/b/b1/Loading_icon.gif)

**Comment by luispadron** [comment]
Thinking about this further I don't think this really makes sense for this project.
This project is meant as a progress ring, like a regular progress bar which will terminate at some point. 

While this sounds like a good idea, I don't think it's worth the development time and bloating the library even more with things when there are a lot of better loading indicators on the web readily available, not to mention the built-in one that Apple provides.

Feel free to discuss if you feel differently, for now I'm closing this.
