### ISSUE TITLE
Cocoapods Version Error

### ISSUE THREAD

**Issue by aliihsanural** [luispadron/UICircularProgressRing#96]
I updated to Cocoapods Version from 1.5.0 to 1.5.3 and it gives an error like this """
.../Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for HomepageVC (8zS-w1-Mfe): dlopen(UICircularProgressRing.framework, 1): no suitable image found.  Did find:
	UICircularProgressRing.framework: required code signature missing for 'UICircularProgressRing.framework'
"""
And after downgrade to cocoapods version . It works properly.

What is the problem ? 

Thank you replies

**Comment by luispadron** [comment]
Please search before posting a new issue: #90
