### ISSUE TITLE
Feature Request: Add Knob For Progress Ring Value

### ISSUE THREAD

**Issue by tushar666** [luispadron/UICircularProgressRing#97]
Can we have a knob for the property -> "value" i.e current value, Well the knob will be an non-interactive.
Please see the below sample image
<img width="129" alt="screen shot 2018-06-01 at 1 29 17 pm" src="https://user-images.githubusercontent.com/5293346/40829130-35188f6a-65a0-11e8-9a13-e3c13e80c066.png">

**Comment by luispadron** [comment]
This seems like a nice feature, I don't have the time right now to work on this but I'll gladly accept pull requests.

**Comment by tushar666** [comment]
Thank you so much @luispadron
