### ISSUE TITLE
How to change progress orientation

### ISSUE THREAD

**Issue by jose920405** [luispadron/UICircularProgressRing#98]
I'm try with `endAngle` and not works.

Example:

```
progressRing.startAngle = -90.0
progressRing.endAngle = 180.0
```

## Version

- Version = 2.1.0

**Comment by RajuD96** [comment]
I want to change the orientation of progress bar like clockwise...how to do that ..?

**Comment by luispadron** [comment]
@RajuD96 Please open up a new issue after reading the docs
